// _varMonitorAttached: object names are registered and renamed by tmcAttach.
function tmcEnsure(generator){generator.addLibrary('tmc_include','#include <TMCStepper.h>');}
function tmcName(block){var field=block.getField('VAR');return field?field.getText():(block.getFieldValue('VAR')||'tmcDriver');}
function tmcAttach(block){if(block._tmcAttached)return;block._tmcAttached=true;block._tmcLast=block.getFieldValue('VAR')||'tmcDriver';if(typeof registerVariableToBlockly==='function')registerVariableToBlockly(block._tmcLast,'TMCStepper');var field=block.getField('VAR');if(!field)return;var original=field.onFinishEditing_;field.onFinishEditing_=function(newName){if(typeof original==='function')original.call(this,newName);if(newName&&newName!==block._tmcLast&&typeof renameVariableInBlockly==='function'){renameVariableInBlockly(block,block._tmcLast,newName,'TMCStepper');block._tmcLast=newName;}};}
Arduino.forBlock['tmc2209_init']=function(block,generator){tmcEnsure(generator);tmcAttach(block);var n=block.getFieldValue('VAR')||'tmcDriver',s=block.getFieldValue('SERIAL')||'Serial1',b=block.getFieldValue('BAUD')||'115200',a=generator.valueToCode(block,'ADDRESS',generator.ORDER_ATOMIC)||'0',r=generator.valueToCode(block,'RSENSE',generator.ORDER_ATOMIC)||'0.11';generator.addObject('tmc2209_'+n,'TMC2209Stepper '+n+'(&'+s+', '+r+', '+a+');');generator.addSetupBegin('tmc2209_serial_'+n,s+'.begin('+b+');');generator.addSetupBegin('tmc2209_begin_'+n,n+'.begin();');return '';};
Arduino.forBlock['tmc2130_init']=function(block,generator){tmcEnsure(generator);tmcAttach(block);generator.addLibrary('tmc_spi','#include <SPI.h>');var n=block.getFieldValue('VAR')||'tmcDriver',c=block.getFieldValue('CS')||'10',r=generator.valueToCode(block,'RSENSE',generator.ORDER_ATOMIC)||'0.11';generator.addObject('tmc2130_'+n,'TMC2130Stepper '+n+'('+c+', '+r+');');generator.addSetupBegin('tmc_spi_begin','SPI.begin();');generator.addSetupBegin('tmc2130_begin_'+n,n+'.begin();');return '';};
Arduino.forBlock['tmc_set_current']=function(block,generator){tmcEnsure(generator);var n=tmcName(block),c=generator.valueToCode(block,'CURRENT',generator.ORDER_ATOMIC)||'600',h=generator.valueToCode(block,'HOLD',generator.ORDER_ATOMIC)||'0.5';return n+'.rms_current('+c+', '+h+');\n';};
Arduino.forBlock['tmc_set_motion']=function(block,generator){tmcEnsure(generator);var n=tmcName(block),m=generator.valueToCode(block,'MICROSTEPS',generator.ORDER_ATOMIC)||'16',t=generator.valueToCode(block,'TOFF',generator.ORDER_ATOMIC)||'5';return n+'.microsteps('+m+');\n'+n+'.toff('+t+');\n';};
Arduino.forBlock['tmc2209_mode']=function(block,generator){tmcEnsure(generator);var n=tmcName(block),m=block.getFieldValue('MODE')||'stealth',a=block.getFieldValue('AUTOSCALE')==='TRUE'?'true':'false';return n+'.en_spreadCycle('+(m==='spread'?'true':'false')+');\n'+n+'.pwm_autoscale('+a+');\n';};
Arduino.forBlock['tmc2209_stall']=function(block,generator){tmcEnsure(generator);var n=tmcName(block),s=generator.valueToCode(block,'SGTHRS',generator.ORDER_ATOMIC)||'80',t=generator.valueToCode(block,'TCOOLTHRS',generator.ORDER_ATOMIC)||'0xFFFFF';return n+'.SGTHRS('+s+');\n'+n+'.TCOOLTHRS('+t+');\n';};
Arduino.forBlock['tmc_read']=function(block,generator){tmcEnsure(generator);var n=tmcName(block),d=block.getFieldValue('DATA')||'DRV_STATUS';var map={DRV_STATUS:n+'.DRV_STATUS()',TSTEP:n+'.TSTEP()',microsteps:n+'.microsteps()',current:n+'.cs2rms('+n+'.cs_actual())'};return [map[d]||map.DRV_STATUS,generator.ORDER_FUNCTION_CALL];};
Arduino.forBlock['tmc_connection']=function(block,generator){tmcEnsure(generator);return [tmcName(block)+'.test_connection()',generator.ORDER_FUNCTION_CALL];};
