// _varMonitorAttached: object names are registered and renamed by microRosAttach.
function microRosEnsure(generator){generator.addLibrary('micro_ros_include','#include <micro_ros_arduino.h>\n#include <rcl/rcl.h>\n#include <rclc/rclc.h>\n#include <rclc/executor.h>\n#include <std_msgs/msg/int32.h>');}
function microRosName(block,field,fallback){var item=block.getField(field);return item?item.getText():(block.getFieldValue(field)||fallback);}
function microRosAttach(block,fieldName,typeName,fallback){var key='_microRos_'+fieldName;if(block[key])return;block[key]=true;var last=key+'_last';block[last]=block.getFieldValue(fieldName)||fallback;if(typeof registerVariableToBlockly==='function')registerVariableToBlockly(block[last],typeName);var field=block.getField(fieldName);if(!field)return;var original=field.onFinishEditing_;field.onFinishEditing_=function(newName){if(typeof original==='function')original.call(this,newName);if(newName&&newName!==block[last]&&typeof renameVariableInBlockly==='function'){renameVariableInBlockly(block,block[last],newName,typeName);block[last]=newName;}};}
Arduino.forBlock['micro_ros_node_init']=function(block,generator){microRosEnsure(generator);microRosAttach(block,'VAR','MicroRosNode','microRos');var n=block.getFieldValue('VAR')||'microRos',name=generator.valueToCode(block,'NAME',generator.ORDER_ATOMIC)||'"aily_node"',ns=generator.valueToCode(block,'NAMESPACE',generator.ORDER_ATOMIC)||'""',h=generator.valueToCode(block,'HANDLES',generator.ORDER_ATOMIC)||'4';generator.addObject('micro_ros_allocator_'+n,'rcl_allocator_t '+n+'_allocator;');generator.addObject('micro_ros_support_'+n,'rclc_support_t '+n+'_support;');generator.addObject('micro_ros_node_'+n,'rcl_node_t '+n+'_node;');generator.addObject('micro_ros_executor_'+n,'rclc_executor_t '+n+'_executor;');generator.addSetupBegin('micro_ros_transport','set_microros_transports();\ndelay(2000);');generator.addSetupBegin('micro_ros_node_setup_'+n,n+'_allocator = rcl_get_default_allocator();\nrclc_support_init(&'+n+'_support, 0, NULL, &'+n+'_allocator);\nrclc_node_init_default(&'+n+'_node, String('+name+').c_str(), String('+ns+').c_str(), &'+n+'_support);\nrclc_executor_init(&'+n+'_executor, &'+n+'_support.context, '+h+', &'+n+'_allocator);');generator.addLoopBegin('micro_ros_spin_'+n,'rclc_executor_spin_some(&'+n+'_executor, RCL_MS_TO_NS(10));');return '';};
Arduino.forBlock['micro_ros_publisher_init']=function(block,generator){microRosEnsure(generator);microRosAttach(block,'VAR','MicroRosPublisher','rosPublisher');var n=block.getFieldValue('VAR')||'rosPublisher',node=microRosName(block,'NODE','microRos'),t=generator.valueToCode(block,'TOPIC',generator.ORDER_ATOMIC)||'"/aily/value"';generator.addObject('micro_ros_pub_'+n,'rcl_publisher_t '+n+';');generator.addObject('micro_ros_pub_msg_'+n,'std_msgs__msg__Int32 '+n+'_msg;');generator.addSetupBegin('micro_ros_pub_init_'+n,'rclc_publisher_init_default(&'+n+', &'+node+'_node, ROSIDL_GET_MSG_TYPE_SUPPORT(std_msgs, msg, Int32), String('+t+').c_str());');return '';};
Arduino.forBlock['micro_ros_publish_int32']=function(block,generator){microRosEnsure(generator);var n=microRosName(block,'VAR','rosPublisher'),v=generator.valueToCode(block,'VALUE',generator.ORDER_ATOMIC)||'0';return n+'_msg.data = (int32_t)('+v+');\nrcl_publish(&'+n+', &'+n+'_msg, NULL);\n';};
Arduino.forBlock['micro_ros_subscriber_init']=function(block,generator){microRosEnsure(generator);microRosAttach(block,'VAR','MicroRosSubscriber','rosSubscriber');var n=block.getFieldValue('VAR')||'rosSubscriber',node=microRosName(block,'NODE','microRos'),t=generator.valueToCode(block,'TOPIC',generator.ORDER_ATOMIC)||'"/aily/command"',body=generator.statementToCode(block,'DO')||'';generator.addObject('micro_ros_sub_'+n,'rcl_subscription_t '+n+';');generator.addObject('micro_ros_sub_msg_'+n,'std_msgs__msg__Int32 '+n+'_msg;');generator.addFunction('micro_ros_sub_callback_'+n,'void '+n+'_callback(const void *msgin) {\n  '+n+'_msg = *(const std_msgs__msg__Int32 *)msgin;\n'+body+'}\n');generator.addSetupBegin('micro_ros_sub_init_'+n,'rclc_subscription_init_default(&'+n+', &'+node+'_node, ROSIDL_GET_MSG_TYPE_SUPPORT(std_msgs, msg, Int32), String('+t+').c_str());\nrclc_executor_add_subscription(&'+node+'_executor, &'+n+', &'+n+'_msg, &'+n+'_callback, ON_NEW_DATA);');return '';};
Arduino.forBlock['micro_ros_received_int32']=function(block,generator){microRosEnsure(generator);return [microRosName(block,'VAR','rosSubscriber')+'_msg.data',generator.ORDER_MEMBER];};
Arduino.forBlock['micro_ros_spin']=function(block,generator){microRosEnsure(generator);var n=microRosName(block,'VAR','microRos'),m=generator.valueToCode(block,'MS',generator.ORDER_ATOMIC)||'10';return 'rclc_executor_spin_some(&'+n+'_executor, RCL_MS_TO_NS('+m+'));\n';};
