// _varMonitorAttached: object names are registered and renamed by firebaseClientAttach.
function firebaseClientEnsure(generator){generator.addLibrary('firebase_wifi','#include <WiFiClientSecure.h>');generator.addLibrary('firebase_client','#include <FirebaseClient.h>');}
function firebaseClientName(block){var field=block.getField('VAR');return field?field.getText():(block.getFieldValue('VAR')||'firebaseApp');}
function firebaseClientAttach(block){if(block._firebaseClientAttached)return;block._firebaseClientAttached=true;block._firebaseClientLast=block.getFieldValue('VAR')||'firebaseApp';if(typeof registerVariableToBlockly==='function')registerVariableToBlockly(block._firebaseClientLast,'FirebaseApp');var field=block.getField('VAR');if(!field)return;var original=field.onFinishEditing_;field.onFinishEditing_=function(newName){if(typeof original==='function')original.call(this,newName);if(newName&&newName!==block._firebaseClientLast&&typeof renameVariableInBlockly==='function'){renameVariableInBlockly(block,block._firebaseClientLast,newName,'FirebaseApp');block._firebaseClientLast=newName;}};}
Arduino.forBlock['firebase_client_init']=function(block,generator){firebaseClientEnsure(generator);firebaseClientAttach(block);var n=block.getFieldValue('VAR')||'firebaseApp',key=generator.valueToCode(block,'API_KEY',generator.ORDER_ATOMIC)||'"WEB_API_KEY"',email=generator.valueToCode(block,'EMAIL',generator.ORDER_ATOMIC)||'"user@example.com"',password=generator.valueToCode(block,'PASSWORD',generator.ORDER_ATOMIC)||'"password"',url=generator.valueToCode(block,'URL',generator.ORDER_ATOMIC)||'"https://project-default-rtdb.firebaseio.com"';generator.addObject('firebase_auth_'+n,'UserAuth '+n+'_auth('+key+', '+email+', '+password+');');generator.addObject('firebase_app_'+n,'FirebaseApp '+n+';');generator.addObject('firebase_ssl_'+n,'WiFiClientSecure '+n+'_ssl;');generator.addObject('firebase_async_'+n,'AsyncClientClass '+n+'_client('+n+'_ssl);');generator.addObject('firebase_db_'+n,'RealtimeDatabase '+n+'_db;');generator.addSetupBegin('firebase_ssl_setup_'+n,n+'_ssl.setInsecure();');generator.addSetupBegin('firebase_init_'+n,'initializeApp('+n+'_client, '+n+', getAuth('+n+'_auth), 120000);\n'+n+'.getApp<RealtimeDatabase>('+n+'_db);\n'+n+'_db.url('+url+');');generator.addLoopBegin('firebase_loop_'+n,n+'.loop();');return '';};
Arduino.forBlock['firebase_client_ready']=function(block,generator){firebaseClientEnsure(generator);return [firebaseClientName(block)+'.ready()',generator.ORDER_FUNCTION_CALL];};
function firebaseClientTypedCall(block,generator,method){firebaseClientEnsure(generator);var n=firebaseClientName(block),type=block.getFieldValue('TYPE')||'String',path=generator.valueToCode(block,'PATH',generator.ORDER_ATOMIC)||'"/data"',value=generator.valueToCode(block,'VALUE',generator.ORDER_NONE)|| (type==='String'?'""':'0');return n+'_db.'+method+'<'+type+'>('+n+'_client, '+path+(method==='get'?'':', ('+type+')('+value+')')+')';}
Arduino.forBlock['firebase_client_set']=function(block,generator){return firebaseClientTypedCall(block,generator,'set')+';\n';};
Arduino.forBlock['firebase_client_get']=function(block,generator){return [firebaseClientTypedCall(block,generator,'get'),generator.ORDER_FUNCTION_CALL];};
Arduino.forBlock['firebase_client_push']=function(block,generator){return firebaseClientTypedCall(block,generator,'push')+';\n';};
Arduino.forBlock['firebase_client_path_action']=function(block,generator){firebaseClientEnsure(generator);var n=firebaseClientName(block),a=block.getFieldValue('ACTION')||'remove',p=generator.valueToCode(block,'PATH',generator.ORDER_ATOMIC)||'"/data"';return [n+'_db.'+a+'('+n+'_client, '+p+')',generator.ORDER_FUNCTION_CALL];};
Arduino.forBlock['firebase_client_last_error']=function(block,generator){firebaseClientEnsure(generator);var n=firebaseClientName(block),d=block.getFieldValue('DATA')||'code';return [n+'_client.lastError().'+d+'()',generator.ORDER_FUNCTION_CALL];};
