// nofrendo generator.js v29 - GB2312 Chinese + ZIP support
Arduino.forBlock['nofrendo_start'] = function(block, generator) {
  const romPath = generator.valueToCode(block, 'ROM_PATH', generator.ORDER_ATOMIC) || '""';
  generator.addLibrary('esp_wifi', '#include <esp_wifi.h>');
  generator.addLibrary('nofrendo_h', '#include <nofrendo.h>');
  generator.addLibrary('FS', '#include <FS.h>');
  generator.addLibrary('SD', '#include <SD.h>');
  generator.addLibrary('SPI', '#include <SPI.h>');
  generator.addLibrary('esp_heap', '#include <esp_heap_caps.h>');
  generator.addLibrary('nofrendo_zip_h', '#include "nofrendo_zip.h"');
  generator.addVariable('nofrendo_fp_extern', 'extern "C" FILE *_nofrendo_preloaded_fp;');
  generator.addVariable('nofrendo_buf_extern', 'extern "C" uint8_t *_nofrendo_preloaded_buf;');
  generator.addVariable('nofrendo_exit_flag', 'extern "C" volatile bool _nofrendo_request_exit;');
  ensureSerialBegin('Serial', generator);

  // Helper: scan directory recursively
  let scanFunc = [];
  scanFunc.push('void _nes_scan_dir(File dir, String basePath, String* names, int* count, int maxCount) {');
  scanFunc.push('  File f=dir.openNextFile();');
  scanFunc.push('  while(f&&(*count)<maxCount){');
  scanFunc.push('    if(f.isDirectory()){');
  scanFunc.push('      _nes_scan_dir(f, basePath+f.name()+"/", names, count, maxCount);');
  scanFunc.push('    }else{');
  scanFunc.push('      String n=f.name();String l=n;l.toLowerCase();');
  scanFunc.push('      if(l.endsWith(".nes")||l.endsWith(".zip")){names[*count]=basePath+n;(*count)++;}');
  scanFunc.push('    }');
  scanFunc.push('    f.close();f=dir.openNextFile();');
  scanFunc.push('  }');
  scanFunc.push('}');
  generator.addFunction('_nes_scan_dir', scanFunc.join('\n'), true);

  // Menu draw helper — uses U8g2_for_TFT_eSPI for GB2312 Chinese text
  let drawFunc = [];
  drawFunc.push('#include "U8g2_for_TFT_eSPI.h"');
  drawFunc.push('#include <stdarg.h>');
  drawFunc.push('#include <string.h>');
  drawFunc.push('extern const uint8_t chinese_city_gb2312[];');
  drawFunc.push('U8g2_for_TFT_eSPI _nes_u8g2;');
  drawFunc.push('void _nes_u8g2_init(){_nes_u8g2.begin(tft);_nes_u8g2.setFont(chinese_city_gb2312);}');
  drawFunc.push('void _nes_print(int x,int y,const char* s,uint16_t fg=TFT_WHITE,uint16_t bg=TFT_BLACK){_nes_u8g2.setFont(chinese_city_gb2312);_nes_u8g2.setFontMode(0);_nes_u8g2.setForegroundColor(fg);_nes_u8g2.setBackgroundColor(bg);_nes_u8g2.setCursor(x,y);_nes_u8g2.print(s);}');
  drawFunc.push('int _nes_printf(int x,int y,uint16_t fg,uint16_t bg,const char* fmt,...){va_list args;va_start(args,fmt);char buf[128];vsnprintf(buf,sizeof(buf),fmt,args);va_end(args);_nes_u8g2.setFont(chinese_city_gb2312);_nes_u8g2.setFontMode(0);_nes_u8g2.setForegroundColor(fg);_nes_u8g2.setBackgroundColor(bg);_nes_u8g2.setCursor(x,y);_nes_u8g2.print(buf);return strlen(buf);}');
  drawFunc.push('void _nes_draw_menu(String* romNames, int romCount, int selIdx, int topOff, int prevSel, int prevTop) {');
  drawFunc.push('  bool fullRedraw=(prevSel<0||prevTop<0||topOff!=prevTop);');
  drawFunc.push('  tft.startWrite();');
  drawFunc.push('  if(fullRedraw){');
  drawFunc.push('    tft.fillRect(0,0,320,240,TFT_BLUE);');
  drawFunc.push('    _nes_printf(5,14,TFT_YELLOW,TFT_BLUE,"\u6e38\u620f\u5217\u8868 (%d/%d)",selIdx+1,romCount);');
  drawFunc.push('    tft.drawLine(0,15,320,15,TFT_YELLOW);');
  drawFunc.push('    _nes_print(5,232,"\u4e0a\u4e0b:\u9009\u62e9 \u5de6\u53f3:\u7ffb\u9875 A:\u5f00\u59cb",TFT_CYAN,TFT_BLUE);');
  drawFunc.push('  }');
  drawFunc.push('  for(int i=0;i<10&&topOff+i<romCount;i++){');
  drawFunc.push('    int ypos=30+i*16;');
  drawFunc.push('    bool sel=(topOff+i==selIdx);');
  drawFunc.push('    bool wasSel=(fullRedraw)?false:(prevTop+i==prevSel);');
  drawFunc.push('    if(!fullRedraw&&sel==wasSel)continue;');
  drawFunc.push('    String nm=romNames[topOff+i];int sl=nm.lastIndexOf(\'/\');if(sl>=0)nm=nm.substring(sl+1);');
  drawFunc.push('    uint16_t bgc=sel?TFT_GREEN:TFT_BLUE;uint16_t fgc=sel?TFT_BLACK:TFT_WHITE;');
  drawFunc.push('    tft.fillRect(0,ypos-12,320,16,bgc);');
  drawFunc.push('    _nes_u8g2.setFont(chinese_city_gb2312);_nes_u8g2.setFontMode(0);_nes_u8g2.setForegroundColor(fgc);_nes_u8g2.setBackgroundColor(bgc);');
  drawFunc.push('    _nes_u8g2.setCursor(3,ypos);_nes_u8g2.printf("%d.",topOff+i+1);');
  drawFunc.push('    _nes_u8g2.setCursor(28,ypos);_nes_u8g2.print(nm);');
  drawFunc.push('  }');
  drawFunc.push('  tft.endWrite();');
  drawFunc.push('}');
  generator.addFunction('_nes_draw_menu', drawFunc.join('\n'), true);

  let lines = [];
  lines.push('// ===NES start===');
  lines.push('Serial.println("[NES] u8g2 init...");');
  lines.push('_nes_u8g2_init();');
  lines.push('Serial.println("[NES] SD reinit...");');
  lines.push('digitalWrite(5,HIGH);');
  lines.push('SD.end();delay(50);');
  lines.push('bool _sdok=SD.begin(22,TFT_eSPI::getSPIinstance());');
  lines.push('Serial.printf("[NES] SD ok=%d\\n",_sdok);');
  lines.push('if(!_sdok){');
  lines.push('  tft.fillScreen(TFT_RED);');
  lines.push('  _nes_print(20,120,"SD\u5361\u521d\u59cb\u5316\u5931\u8d25!",TFT_WHITE,TFT_RED);while(1)delay(1000);');
  lines.push('}');
  lines.push('Serial.println("[NES] pin setup...");');
  lines.push('pinMode(2,INPUT_PULLUP);pinMode(13,INPUT_PULLUP);pinMode(27,INPUT_PULLUP);pinMode(35,INPUT);pinMode(12,INPUT_PULLUP);pinMode(34,INPUT);');

  // ROM browser menu
  lines.push('Serial.println("[NES] entering ROM loop...");');
  lines.push('while(true){');
  lines.push('  String romNames[64];int romCount=0;');
  lines.push('  File dir1=SD.open("/roms/nes");');
  lines.push('  if(dir1){_nes_scan_dir(dir1,"/roms/nes/",romNames,&romCount,64);dir1.close();}');
  lines.push('  if(romCount==0){File dir2=SD.open("/");if(dir2){_nes_scan_dir(dir2,"/",romNames,&romCount,64);dir2.close();}}');
  lines.push('  if(romCount==0){');
  lines.push('    tft.fillScreen(TFT_RED);');
  lines.push('    _nes_print(20,90,"\u672a\u627e\u5230\u6e38\u620f!",TFT_WHITE,TFT_RED);');
  lines.push('    _nes_print(10,130,"\u8bf7\u5c06.nes\u653e\u5165/roms/nes/",TFT_WHITE,TFT_RED);delay(5000);continue;}');
  // Menu
  lines.push('  int selIdx=0;bool launched=false;int topOff=0;int prevSel=-1;int prevTop=-1;');
  lines.push('  while(!launched){');
  lines.push('    if(selIdx<topOff)topOff=selIdx;');
  lines.push('    if(selIdx>=topOff+10)topOff=selIdx;');
  lines.push('    if(selIdx!=prevSel||topOff!=prevTop){');
  lines.push('      _nes_draw_menu(romNames,romCount,selIdx,topOff,prevSel,prevTop);');
  lines.push('      prevSel=selIdx;prevTop=topOff;}');
  lines.push('    delay(120);');
  lines.push('    if(digitalRead(2)==LOW){while(digitalRead(2)==LOW)delay(10);selIdx--;if(selIdx<0)selIdx=romCount-1;}');
  lines.push('    if(digitalRead(13)==LOW){while(digitalRead(13)==LOW)delay(10);selIdx++;if(selIdx>=romCount)selIdx=0;}');
  lines.push('    if(digitalRead(27)==LOW){while(digitalRead(27)==LOW)delay(10);selIdx-=10;if(selIdx<0)selIdx=0;}');
  lines.push('    if(digitalRead(35)==LOW){while(digitalRead(35)==LOW)delay(10);selIdx+=10;if(selIdx>=romCount)selIdx=romCount-1;}');
  lines.push('    if(digitalRead(34)==LOW){');
  lines.push('      delay(300);launched=true;');
  // Launch ROM with debug info
  lines.push('      String chosen=romNames[selIdx];');
  lines.push('      String chosenLower=chosen;chosenLower.toLowerCase();');
  lines.push('      bool isZip=chosenLower.endsWith(".zip");');
  lines.push('      File _nf=SD.open(chosen.c_str());');
  lines.push('      if(!_nf||_nf.size()==0){tft.fillScreen(TFT_RED);_nes_print(40,100,"\u6253\u5f00\u5931\u8d25!",TFT_WHITE,TFT_RED);delay(2000);break;}');
  lines.push('      size_t _nfs=_nf.size();');
  lines.push('      uint8_t *_nfb=(uint8_t*)heap_caps_malloc(_nfs,MALLOC_CAP_SPIRAM|MALLOC_CAP_8BIT);');
  lines.push('      if(!_nfb){tft.fillScreen(TFT_RED);_nes_print(40,100,"\u5185\u5b58\u4e0d\u8db3!",TFT_WHITE,TFT_RED);delay(3000);break;}');
  lines.push('      _nf.read(_nfb,_nfs);_nf.close();');
  lines.push('      if(isZip){');
  lines.push('        uint8_t *_unzipped=NULL;uint32_t _uzsize=0;');
  lines.push('        int zr=zip_extract_nes(&_unzipped,&_uzsize,_nfb,_nfs);');
  lines.push('        free(_nfb);');
  lines.push('        if(zr!=0||!_unzipped){tft.fillScreen(TFT_RED);_nes_print(40,80,"ZIP\u89e3\u538b\u5931\u8d25!",TFT_WHITE,TFT_RED);_nes_printf(40,120,TFT_WHITE,TFT_RED,"\u9519\u8bef\u7801: %d",zr);_nes_printf(40,140,TFT_WHITE,TFT_RED,"ZIP\u5927\u5c0f: %d bytes",(int)_nfs);delay(5000);break;}');
  lines.push('        _nfb=_unzipped;_nfs=_uzsize;');
  lines.push('      }');
  lines.push('      _nofrendo_preloaded_fp=fmemopen(_nfb,_nfs,"rb");');
  lines.push('      _nofrendo_preloaded_buf=_nfb;');
  // Debug: show iNES header
  lines.push('      tft.fillScreen(TFT_BLACK);tft.setCursor(0,0);tft.setTextColor(TFT_WHITE,TFT_BLACK);tft.setTextSize(1);');
  lines.push('      uint8_t prgBanks=_nfb[4];uint8_t chrBanks=_nfb[5];uint8_t mapper=(_nfb[6]>>4)|(_nfb[7]&0xF0);');
  lines.push('      tft.printf("PRG:%d(%dKB) CHR:%d(%dKB)\\n",prgBanks,prgBanks*16,chrBanks,chrBanks*8);');
  lines.push('      tft.printf("Mapper:%d PSRAM:%dKB\\n",mapper,(unsigned)ESP.getFreePsram()/1024);');
  lines.push('      delay(3000);');
  lines.push('      Serial.println("[NES] launching nofrendo_main...");');
  lines.push('      _nofrendo_request_exit=false;');
  lines.push('      SD.mkdir("/roms/nes/saves");');
  lines.push('      esp_wifi_deinit();disableCore0WDT();disableCore1WDT();');
  lines.push('      char _pathBuf[128];strncpy(_pathBuf,chosen.c_str(),127);_pathBuf[127]=0;');
  lines.push('      char *_na[2];_na[0]=_pathBuf;_na[1]=NULL;');
  lines.push('      nofrendo_main(1,_na);');
  lines.push('      if(_nofrendo_preloaded_fp){fclose(_nofrendo_preloaded_fp);_nofrendo_preloaded_fp=NULL;}');
  lines.push('      free(_nfb);_nofrendo_preloaded_buf=NULL;');
  lines.push('      // Re-init SD after exit');
  lines.push('      SD.end();delay(50);SD.begin(22,TFT_eSPI::getSPIinstance());');
  lines.push('    }');
  lines.push('  }');
  lines.push('}');
  return lines.join('\n') + '\n';
};

Arduino.forBlock['nofrendo_find_rom'] = function(block, generator) {
  generator.addLibrary('SD', '#include <SD.h>');
  generator.addLibrary('SPI', '#include <SPI.h>');
  let func = [];
  func.push('String nofrendo_find_rom_file() {');
  func.push('  File root = SD.open("/");if(!root)return"";');
  func.push('  File file=root.openNextFile();while(file){');
  func.push('    if(!file.isDirectory()){String n=file.name();String l=n;l.toLowerCase();');
  func.push('      if(l.endsWith(".nes")){String p="/"+n;file.close();return p;}}');
  func.push('    file=root.openNextFile();}return"";');
  func.push('}');
  generator.addFunction('nofrendo_find_rom', func.join('\n'), true);
  return ['nofrendo_find_rom_file()', generator.ORDER_ATOMIC];
};
