// _varMonitorAttached: object names are registered and renamed by audioToolsAttach.
function audioToolsEnsure(generator){generator.addLibrary('audio_tools_include','#include <AudioTools.h>');}
function audioToolsName(block,field,fallback){var item=block.getField(field);return item?item.getText():(block.getFieldValue(field)||fallback);}
function audioToolsAttach(block,fieldName,typeName,fallback){var key='_audioTools_'+fieldName;if(block[key])return;block[key]=true;var last=key+'_last';block[last]=block.getFieldValue(fieldName)||fallback;if(typeof registerVariableToBlockly==='function')registerVariableToBlockly(block[last],typeName);var field=block.getField(fieldName);if(!field)return;var original=field.onFinishEditing_;field.onFinishEditing_=function(newName){if(typeof original==='function')original.call(this,newName);if(newName&&newName!==block[last]&&typeof renameVariableInBlockly==='function'){renameVariableInBlockly(block,block[last],newName,typeName);block[last]=newName;}};}
Arduino.forBlock['audio_tools_i2s_init']=function(block,generator){audioToolsEnsure(generator);audioToolsAttach(block,'VAR','I2SStream','i2sAudio');var n=block.getFieldValue('VAR')||'i2sAudio',m=block.getFieldValue('MODE')||'TX_MODE',r=generator.valueToCode(block,'RATE',generator.ORDER_ATOMIC)||'44100',c=generator.valueToCode(block,'CHANNELS',generator.ORDER_ATOMIC)||'2',bits=generator.valueToCode(block,'BITS',generator.ORDER_ATOMIC)||'16',b=block.getFieldValue('BCLK')||'15',w=block.getFieldValue('WS')||'14',tx=block.getFieldValue('TX')||'22',rx=block.getFieldValue('RX')||'23';generator.addObject('audio_tools_i2s_'+n,'I2SStream '+n+';');generator.addSetupBegin('audio_tools_i2s_begin_'+n,'auto '+n+'_config = '+n+'.defaultConfig('+m+');\n'+n+'_config.sample_rate = '+r+';\n'+n+'_config.channels = '+c+';\n'+n+'_config.bits_per_sample = '+bits+';\n'+n+'_config.pin_bck = '+b+';\n'+n+'_config.pin_ws = '+w+';\n'+n+'_config.pin_data = '+tx+';\n'+n+'_config.pin_data_rx = '+rx+';\n'+n+'.begin('+n+'_config);');return '';};
Arduino.forBlock['audio_tools_copy_init']=function(block,generator){audioToolsEnsure(generator);audioToolsAttach(block,'VAR','StreamCopy','audioCopier');var n=block.getFieldValue('VAR')||'audioCopier',o=audioToolsName(block,'OUT','i2sOut'),i=audioToolsName(block,'IN','i2sIn'),a=block.getFieldValue('AUTO')==='TRUE';generator.addObject('audio_tools_copy_'+n,'StreamCopy '+n+'('+o+', '+i+');');if(a)generator.addLoopBegin('audio_tools_copy_loop_'+n,n+'.copy();');return '';};
Arduino.forBlock['audio_tools_copy']=function(block,generator){audioToolsEnsure(generator);return audioToolsName(block,'VAR','audioCopier')+'.copy();\n';};
Arduino.forBlock['audio_tools_write_sample']=function(block,generator){audioToolsEnsure(generator);var n=audioToolsName(block,'VAR','i2sAudio'),s=generator.valueToCode(block,'SAMPLE',generator.ORDER_ATOMIC)||'0';generator.addVariable('audio_tools_sample_out','int16_t _ailyAudioSampleOut = 0;');return '_ailyAudioSampleOut = (int16_t)('+s+');\n'+n+'.write((uint8_t*)&_ailyAudioSampleOut, sizeof(_ailyAudioSampleOut));\n';};
Arduino.forBlock['audio_tools_read_sample']=function(block,generator){audioToolsEnsure(generator);var n=audioToolsName(block,'VAR','i2sAudio');generator.addVariable('audio_tools_sample_in','int16_t _ailyAudioSampleIn = 0;');return ['('+n+'.readBytes((uint8_t*)&_ailyAudioSampleIn, sizeof(_ailyAudioSampleIn)), _ailyAudioSampleIn)',generator.ORDER_COMMA];};
Arduino.forBlock['audio_tools_available']=function(block,generator){audioToolsEnsure(generator);return [audioToolsName(block,'VAR','i2sAudio')+'.available()',generator.ORDER_FUNCTION_CALL];};
Arduino.forBlock['audio_tools_end']=function(block,generator){audioToolsEnsure(generator);return audioToolsName(block,'VAR','i2sAudio')+'.end();\n';};
