'use strict';

function esp8266SpiSlaveInclude(generator) { generator.addLibrary('ESP8266_SPISlave', '#include <SPISlave.h>'); }
Arduino.forBlock['esp8266_spislave_begin'] = function(block, generator) { esp8266SpiSlaveInclude(generator); return 'SPISlave.begin(' + (block.getFieldValue('LENGTH') || '4') + ');\n'; };
Arduino.forBlock['esp8266_spislave_end'] = function(block, generator) { esp8266SpiSlaveInclude(generator); return 'SPISlave.end();\n'; };
Arduino.forBlock['esp8266_spislave_set_data'] = function(block, generator) { esp8266SpiSlaveInclude(generator); const d = generator.valueToCode(block, 'DATA', generator.ORDER_ATOMIC) || '""'; return '{ String esp8266SpiSlaveData = String(' + d + '); SPISlave.setData(esp8266SpiSlaveData.c_str()); }\n'; };
Arduino.forBlock['esp8266_spislave_set_status'] = function(block, generator) { esp8266SpiSlaveInclude(generator); return 'SPISlave.setStatus((uint32_t)(' + (generator.valueToCode(block, 'STATUS', generator.ORDER_ATOMIC) || '0') + '));\n'; };
Arduino.forBlock['esp8266_spislave_on_data'] = function(block, generator) { esp8266SpiSlaveInclude(generator); const body = generator.statementToCode(block, 'HANDLER') || ''; generator.addFunction('esp8266_spislave_data_cb', 'void esp8266SpiSlaveDataCallback(uint8_t *data, size_t len) {\n' + body + '}'); generator.addSetupEnd('esp8266_spislave_data_hook', 'SPISlave.onData(esp8266SpiSlaveDataCallback);'); return ''; };
Arduino.forBlock['esp8266_spislave_on_status'] = function(block, generator) { esp8266SpiSlaveInclude(generator); const body = generator.statementToCode(block, 'HANDLER') || ''; generator.addFunction('esp8266_spislave_status_cb', 'void esp8266SpiSlaveStatusCallback(uint32_t status) {\n' + body + '}'); generator.addSetupEnd('esp8266_spislave_status_hook', 'SPISlave.onStatus(esp8266SpiSlaveStatusCallback);'); return ''; };
Arduino.forBlock['esp8266_spislave_on_data_sent'] = function(block, generator) { esp8266SpiSlaveInclude(generator); const body = generator.statementToCode(block, 'HANDLER') || ''; generator.addFunction('esp8266_spislave_data_sent_cb', 'void esp8266SpiSlaveDataSentCallback() {\n' + body + '}'); generator.addSetupEnd('esp8266_spislave_data_sent_hook', 'SPISlave.onDataSent(esp8266SpiSlaveDataSentCallback);'); return ''; };
Arduino.forBlock['esp8266_spislave_on_status_sent'] = function(block, generator) { esp8266SpiSlaveInclude(generator); const body = generator.statementToCode(block, 'HANDLER') || ''; generator.addFunction('esp8266_spislave_status_sent_cb', 'void esp8266SpiSlaveStatusSentCallback() {\n' + body + '}'); generator.addSetupEnd('esp8266_spislave_status_sent_hook', 'SPISlave.onStatusSent(esp8266SpiSlaveStatusSentCallback);'); return ''; };
Arduino.forBlock['esp8266_spislave_received_text'] = function(block, generator) { return ['String((char *)data)', generator.ORDER_FUNCTION_CALL]; };
Arduino.forBlock['esp8266_spislave_received_length'] = function(block, generator) { return ['len', generator.ORDER_ATOMIC]; };
Arduino.forBlock['esp8266_spislave_received_status'] = function(block, generator) { return ['status', generator.ORDER_ATOMIC]; };
