// _varMonitorAttached: object names are registered and renamed by espTfliteAttach.
function espTfliteEnsure(generator){generator.addLibrary('esp_tflite_core','#include "tensorflow/lite/micro/micro_mutable_op_resolver.h"\n#include "tensorflow/lite/micro/micro_interpreter.h"\n#include "tensorflow/lite/schema/schema_generated.h"');generator.addFunction('esp_tflite_element_count','int _ailyTfliteElementCount(const TfLiteTensor *tensor) {\n  if (!tensor || !tensor->dims) return 0;\n  int count = 1;\n  for (int i = 0; i < tensor->dims->size; ++i) count *= tensor->dims->data[i];\n  return count;\n}');}
function espTfliteName(block){var field=block.getField('VAR');return field?field.getText():(block.getFieldValue('VAR')||'tflm');}
function espTfliteAttach(block){if(block._espTfliteAttached)return;block._espTfliteAttached=true;block._espTfliteLast=block.getFieldValue('VAR')||'tflm';if(typeof registerVariableToBlockly==='function')registerVariableToBlockly(block._espTfliteLast,'TFLiteMicro');var field=block.getField('VAR');if(!field)return;var original=field.onFinishEditing_;field.onFinishEditing_=function(newName){if(typeof original==='function')original.call(this,newName);if(newName&&newName!==block._espTfliteLast&&typeof renameVariableInBlockly==='function'){renameVariableInBlockly(block,block._espTfliteLast,newName,'TFLiteMicro');block._espTfliteLast=newName;}};}
Arduino.forBlock['esp_tflite_init']=function(block,generator){espTfliteEnsure(generator);espTfliteAttach(block);var n=block.getFieldValue('VAR')||'tflm',h=(block.getFieldValue('HEADER')||'model.h').replace(/[^A-Za-z0-9_./-]/g,''),m=(block.getFieldValue('MODEL')||'g_model').replace(/[^A-Za-z0-9_]/g,''),a=block.getFieldValue('ARENA')||65536;generator.addLibrary('esp_tflite_model_'+n,'#include "'+h+'"');generator.addObject('esp_tflite_model_ptr_'+n,'const tflite::Model *'+n+'_model = nullptr;');generator.addObject('esp_tflite_resolver_'+n,'tflite::MicroMutableOpResolver<16> '+n+'_resolver;');generator.addObject('esp_tflite_arena_'+n,'alignas(16) uint8_t '+n+'_arena['+a+'];');generator.addObject('esp_tflite_interpreter_'+n,'tflite::MicroInterpreter *'+n+'_interpreter = nullptr;');generator.addObject('esp_tflite_tensors_'+n,'TfLiteTensor *'+n+'_input = nullptr;\nTfLiteTensor *'+n+'_output = nullptr;\nbool '+n+'_ready = false;');generator.addSetupBegin('esp_tflite_ops_'+n,n+'_resolver.AddFullyConnected();\n'+n+'_resolver.AddConv2D();\n'+n+'_resolver.AddDepthwiseConv2D();\n'+n+'_resolver.AddMaxPool2D();\n'+n+'_resolver.AddAveragePool2D();\n'+n+'_resolver.AddReshape();\n'+n+'_resolver.AddSoftmax();\n'+n+'_resolver.AddQuantize();\n'+n+'_resolver.AddDequantize();\n'+n+'_resolver.AddAdd();\n'+n+'_resolver.AddMul();');generator.addSetupBegin('esp_tflite_init_'+n,n+'_model = tflite::GetModel('+m+');\nif ('+n+'_model && '+n+'_model->version() == TFLITE_SCHEMA_VERSION) {\n  '+n+'_interpreter = new tflite::MicroInterpreter('+n+'_model, '+n+'_resolver, '+n+'_arena, sizeof('+n+'_arena));\n  '+n+'_ready = ('+n+'_interpreter->AllocateTensors() == kTfLiteOk);\n  if ('+n+'_ready) { '+n+'_input = '+n+'_interpreter->input(0); '+n+'_output = '+n+'_interpreter->output(0); }\n}');return '';};
Arduino.forBlock['esp_tflite_input_set']=function(block,generator){espTfliteEnsure(generator);var n=espTfliteName(block),i=generator.valueToCode(block,'INDEX',generator.ORDER_ATOMIC)||'0',t=block.getFieldValue('TYPE')||'float',v=generator.valueToCode(block,'VALUE',generator.ORDER_ATOMIC)||'0';var map={float:n+'_input->data.f['+i+'] = (float)('+v+');',int8:n+'_input->data.int8['+i+'] = (int8_t)('+v+');',uint8:n+'_input->data.uint8['+i+'] = (uint8_t)('+v+');',quantized:n+'_input->data.int8['+i+'] = (int8_t)(('+v+') / '+n+'_input->params.scale + '+n+'_input->params.zero_point);'};return 'if ('+n+'_ready) '+(map[t]||map.float)+'\n';};
Arduino.forBlock['esp_tflite_invoke']=function(block,generator){espTfliteEnsure(generator);var n=espTfliteName(block);return ['('+n+'_ready && '+n+'_interpreter->Invoke() == kTfLiteOk)',generator.ORDER_LOGICAL_AND];};
Arduino.forBlock['esp_tflite_output_get']=function(block,generator){espTfliteEnsure(generator);var n=espTfliteName(block),i=generator.valueToCode(block,'INDEX',generator.ORDER_ATOMIC)||'0',t=block.getFieldValue('TYPE')||'float';var map={float:n+'_output->data.f['+i+']',int8:n+'_output->data.int8['+i+']',uint8:n+'_output->data.uint8['+i+']',dequantized:'(('+n+'_output->data.int8['+i+'] - '+n+'_output->params.zero_point) * '+n+'_output->params.scale)'};return ['('+n+'_ready ? '+(map[t]||map.float)+' : 0)',generator.ORDER_CONDITIONAL];};
Arduino.forBlock['esp_tflite_tensor_info']=function(block,generator){espTfliteEnsure(generator);var n=espTfliteName(block),t=block.getFieldValue('TENSOR')||'input',i=block.getFieldValue('INFO')||'bytes',p=n+'_'+t;var map={bytes:p+'->bytes',count:'_ailyTfliteElementCount('+p+')',type:p+'->type',scale:p+'->params.scale',zero_point:p+'->params.zero_point'};return ['('+n+'_ready ? '+(map[i]||map.bytes)+' : 0)',generator.ORDER_CONDITIONAL];};
Arduino.forBlock['esp_tflite_ready']=function(block,generator){return [espTfliteName(block)+'_ready',generator.ORDER_ATOMIC];};
