// _varMonitorAttached: object names are registered and renamed by tinyusbAttach.
function tinyusbEnsure(generator){generator.addLibrary('tinyusb_include','#include <Adafruit_TinyUSB.h>');}
function tinyusbName(block){var field=block.getField('VAR');return field?field.getText():(block.getFieldValue('VAR')||'webUsb');}
function tinyusbAttach(block,typeName,fallback){if(block._tinyusbAttached)return;block._tinyusbAttached=true;block._tinyusbLast=block.getFieldValue('VAR')||fallback;if(typeof registerVariableToBlockly==='function')registerVariableToBlockly(block._tinyusbLast,typeName);var field=block.getField('VAR');if(!field)return;var original=field.onFinishEditing_;field.onFinishEditing_=function(newName){if(typeof original==='function')original.call(this,newName);if(newName&&newName!==block._tinyusbLast&&typeof renameVariableInBlockly==='function'){renameVariableInBlockly(block,block._tinyusbLast,newName,typeName);block._tinyusbLast=newName;}};}
function tinyusbBegin(generator){generator.addSetupBegin('tinyusb_begin','if (!TinyUSBDevice.isInitialized()) TinyUSBDevice.begin(0);');generator.addLoopBegin('tinyusb_task','#ifdef TINYUSB_NEED_POLLING_TASK\nTinyUSBDevice.task();\n#endif');}
Arduino.forBlock['tinyusb_device_init']=function(block,generator){tinyusbEnsure(generator);tinyusbBegin(generator);var v=generator.valueToCode(block,'VID',generator.ORDER_ATOMIC)||'0x239A',p=generator.valueToCode(block,'PID',generator.ORDER_ATOMIC)||'0x00B3',m=generator.valueToCode(block,'MANUFACTURER',generator.ORDER_ATOMIC)||'"Aily"',n=generator.valueToCode(block,'PRODUCT',generator.ORDER_ATOMIC)||'"Blockly USB Device"';generator.addObject('tinyusb_descriptor_strings','String _ailyTinyUsbManufacturer;\nString _ailyTinyUsbProduct;');generator.addSetupBegin('tinyusb_descriptors','_ailyTinyUsbManufacturer = '+m+';\n_ailyTinyUsbProduct = '+n+';\nTinyUSBDevice.setID('+v+', '+p+');\nTinyUSBDevice.setManufacturerDescriptor(_ailyTinyUsbManufacturer.c_str());\nTinyUSBDevice.setProductDescriptor(_ailyTinyUsbProduct.c_str());');return '';};
Arduino.forBlock['tinyusb_webusb_init']=function(block,generator){tinyusbEnsure(generator);tinyusbBegin(generator);tinyusbAttach(block,'Adafruit_USBD_WebUSB','webUsb');var n=block.getFieldValue('VAR')||'webUsb',h=(block.getFieldValue('HOST')||'example.tinyusb.org/webusb-serial/index.html').replace(/[^A-Za-z0-9_./?&=:#-]/g,'');generator.addMacro('tinyusb_url_'+n,'WEBUSB_URL_DEF('+n+'_landing, 1, "'+h+'");');generator.addObject('tinyusb_web_'+n,'Adafruit_USBD_WebUSB '+n+';');generator.addSetupBegin('tinyusb_web_begin_'+n,n+'.setLandingPage(&'+n+'_landing);\n'+n+'.begin();');return '';};
Arduino.forBlock['tinyusb_webusb_write']=function(block,generator){tinyusbEnsure(generator);var n=tinyusbName(block),o=block.getFieldValue('OP')||'print',d=generator.valueToCode(block,'DATA',generator.ORDER_NONE)||'""';return n+'.'+o+'('+d+');\n'+n+'.flush();\n';};
Arduino.forBlock['tinyusb_webusb_data']=function(block,generator){tinyusbEnsure(generator);var n=tinyusbName(block),d=block.getFieldValue('DATA')||'available';return [n+'.'+d+'()',generator.ORDER_FUNCTION_CALL];};
Arduino.forBlock['tinyusb_midi_init']=function(block,generator){tinyusbEnsure(generator);tinyusbBegin(generator);generator.addLibrary('tinyusb_midi_library','#include <MIDI.h>');tinyusbAttach(block,'TinyUSBMIDI','usbMidi');var n=block.getFieldValue('VAR')||'usbMidi';generator.addObject('tinyusb_midi_transport_'+n,'Adafruit_USBD_MIDI '+n+'_transport;');generator.addObject('tinyusb_midi_'+n,'MIDI_CREATE_INSTANCE(Adafruit_USBD_MIDI, '+n+'_transport, '+n+');');generator.addSetupBegin('tinyusb_midi_begin_'+n,n+'.begin(MIDI_CHANNEL_OMNI);');generator.addLoopBegin('tinyusb_midi_read_'+n,n+'.read();');return '';};
Arduino.forBlock['tinyusb_midi_note']=function(block,generator){tinyusbEnsure(generator);var n=tinyusbName(block),a=block.getFieldValue('ACTION')||'sendNoteOn',note=generator.valueToCode(block,'NOTE',generator.ORDER_ATOMIC)||'60',v=generator.valueToCode(block,'VELOCITY',generator.ORDER_ATOMIC)||'127',c=generator.valueToCode(block,'CHANNEL',generator.ORDER_ATOMIC)||'1';return n+'.'+a+'('+note+', '+v+', '+c+');\n';};
Arduino.forBlock['tinyusb_midi_control']=function(block,generator){tinyusbEnsure(generator);var n=tinyusbName(block),c=generator.valueToCode(block,'CONTROL',generator.ORDER_ATOMIC)||'1',v=generator.valueToCode(block,'VALUE',generator.ORDER_ATOMIC)||'0',ch=generator.valueToCode(block,'CHANNEL',generator.ORDER_ATOMIC)||'1';return n+'.sendControlChange('+c+', '+v+', '+ch+');\n';};
Arduino.forBlock['tinyusb_mounted']=function(block,generator){tinyusbEnsure(generator);return ['TinyUSBDevice.mounted()',generator.ORDER_FUNCTION_CALL];};
