// _varMonitorAttached: object names are registered and renamed by espAudioAttach.
function espAudioEnsure(generator){generator.addLibrary('esp_audio_include','#include <Audio.h>');}
function espAudioName(block){var field=block.getField('VAR');return field?field.getText():(block.getFieldValue('VAR')||'audio');}
function espAudioAttach(block){if(block._espAudioAttached)return;block._espAudioAttached=true;block._espAudioLast=block.getFieldValue('VAR')||'audio';if(typeof registerVariableToBlockly==='function')registerVariableToBlockly(block._espAudioLast,'Audio');var field=block.getField('VAR');if(!field)return;var original=field.onFinishEditing_;field.onFinishEditing_=function(newName){if(typeof original==='function')original.call(this,newName);if(newName&&newName!==block._espAudioLast&&typeof renameVariableInBlockly==='function'){renameVariableInBlockly(block,block._espAudioLast,newName,'Audio');block._espAudioLast=newName;}};}
Arduino.forBlock['esp_audio_init']=function(block,generator){espAudioEnsure(generator);espAudioAttach(block);var n=block.getFieldValue('VAR')||'audio',b=block.getFieldValue('BCLK')||'26',l=block.getFieldValue('LRCLK')||'25',d=block.getFieldValue('DOUT')||'22',v=generator.valueToCode(block,'VOLUME',generator.ORDER_ATOMIC)||'12';generator.addObject('esp_audio_'+n,'Audio '+n+';');generator.addSetupBegin('esp_audio_setup_'+n,n+'.setPinout('+b+', '+l+', '+d+');\n'+n+'.setVolume('+v+');');generator.addLoopBegin('esp_audio_loop_'+n,n+'.loop();');return '';};
Arduino.forBlock['esp_audio_stream']=function(block,generator){espAudioEnsure(generator);var n=espAudioName(block),u=generator.valueToCode(block,'URL',generator.ORDER_ATOMIC)||'"http://example.com/stream.mp3"';return n+'.connecttohost('+u+');\n';};
Arduino.forBlock['esp_audio_file']=function(block,generator){espAudioEnsure(generator);var n=espAudioName(block),f=block.getFieldValue('FS')||'SD',p=generator.valueToCode(block,'PATH',generator.ORDER_ATOMIC)||'"/audio.mp3"';generator.addLibrary('esp_audio_fs_'+f,'#include <'+(f==='SD_MMC'?'SD_MMC.h':f+'.h')+'>');return n+'.connecttoFS('+f+', '+p+');\n';};
Arduino.forBlock['esp_audio_control']=function(block,generator){espAudioEnsure(generator);var n=espAudioName(block),a=block.getFieldValue('ACTION')||'pauseResume';return n+'.'+a+'();\n';};
Arduino.forBlock['esp_audio_set']=function(block,generator){espAudioEnsure(generator);var n=espAudioName(block),s=block.getFieldValue('SETTING')||'setVolume',v=generator.valueToCode(block,'VALUE',generator.ORDER_ATOMIC)||'12';return n+'.'+s+'('+v+');\n';};
Arduino.forBlock['esp_audio_state']=function(block,generator){espAudioEnsure(generator);var n=espAudioName(block),s=block.getFieldValue('STATE')||'isRunning';return [n+'.'+s+'()',generator.ORDER_FUNCTION_CALL];};
