// _varMonitorAttached: object names are registered and renamed by influxAttach.
function influxEnsure(generator){generator.addLibrary('influx_include','#include <InfluxDbClient.h>');}
function influxName(block,field,fallback){var item=block.getField(field);return item?item.getText():(block.getFieldValue(field)||fallback);}
function influxAttach(block,fieldName,typeName,fallback){var key='_influx_'+fieldName;if(block[key])return;block[key]=true;var last=key+'_last';block[last]=block.getFieldValue(fieldName)||fallback;if(typeof registerVariableToBlockly==='function')registerVariableToBlockly(block[last],typeName);var field=block.getField(fieldName);if(!field)return;var original=field.onFinishEditing_;field.onFinishEditing_=function(newName){if(typeof original==='function')original.call(this,newName);if(newName&&newName!==block[last]&&typeof renameVariableInBlockly==='function'){renameVariableInBlockly(block,block[last],newName,typeName);block[last]=newName;}};}
Arduino.forBlock['influxdb_init']=function(block,generator){influxEnsure(generator);influxAttach(block,'VAR','InfluxDBClient','influx');var n=block.getFieldValue('VAR')||'influx',u=generator.valueToCode(block,'URL',generator.ORDER_ATOMIC)||'"http://192.168.1.10:8086"',o=generator.valueToCode(block,'ORG',generator.ORDER_ATOMIC)||'"org"',b=generator.valueToCode(block,'BUCKET',generator.ORDER_ATOMIC)||'"bucket"',t=generator.valueToCode(block,'TOKEN',generator.ORDER_ATOMIC)||'"token"';generator.addObject('influx_client_'+n,'InfluxDBClient '+n+'('+u+', '+o+', '+b+', '+t+');');return '';};
Arduino.forBlock['influxdb_point_init']=function(block,generator){influxEnsure(generator);influxAttach(block,'VAR','Point','sensorPoint');var n=block.getFieldValue('VAR')||'sensorPoint',m=generator.valueToCode(block,'MEASUREMENT',generator.ORDER_ATOMIC)||'"sensor"';generator.addObject('influx_point_'+n,'Point '+n+'('+m+');');return '';};
Arduino.forBlock['influxdb_point_add']=function(block,generator){influxEnsure(generator);var n=influxName(block,'VAR','sensorPoint'),k=block.getFieldValue('KIND')||'addField',key=generator.valueToCode(block,'KEY',generator.ORDER_ATOMIC)||'"value"',v=generator.valueToCode(block,'VALUE',generator.ORDER_NONE)||'0';return n+'.'+k+'('+key+', '+v+');\n';};
Arduino.forBlock['influxdb_point_clear']=function(block,generator){influxEnsure(generator);var n=influxName(block,'VAR','sensorPoint'),k=block.getFieldValue('KIND')||'clearFields';return n+'.'+k+'();\n';};
Arduino.forBlock['influxdb_write']=function(block,generator){influxEnsure(generator);var c=influxName(block,'CLIENT','influx'),p=influxName(block,'POINT','sensorPoint');return [c+'.writePoint('+p+')',generator.ORDER_FUNCTION_CALL];};
Arduino.forBlock['influxdb_validate']=function(block,generator){influxEnsure(generator);return [influxName(block,'VAR','influx')+'.validateConnection()',generator.ORDER_FUNCTION_CALL];};
Arduino.forBlock['influxdb_info']=function(block,generator){influxEnsure(generator);var n=influxName(block,'VAR','influx'),i=block.getFieldValue('INFO')||'getLastErrorMessage';return [n+'.'+i+'()',generator.ORDER_FUNCTION_CALL];};
Arduino.forBlock['influxdb_line_protocol']=function(block,generator){influxEnsure(generator);var c=influxName(block,'CLIENT','influx'),p=influxName(block,'POINT','sensorPoint');return [c+'.pointToLineProtocol('+p+')',generator.ORDER_FUNCTION_CALL];};
