function addJpegViewerInfra(generator) {
  generator.addLibrary('TFT_eSPI', '#include <TFT_eSPI.h>');
  generator.addLibrary('SD', '#include <SD.h>');
  generator.addLibrary('FS', '#include <FS.h>');
  generator.addLibrary('tjpgd', '#include "tjpgd.h"');
  generator.addLibrary('ProgJpegFull', '#include "ProgJpegFull.h"');

  let fn = '';
  fn += 'extern void epubCovRelease() __attribute__((weak));\n';
  fn += 'extern void epubImgRelease() __attribute__((weak));\n';
  fn += 'static const uint8_t* jpgv_jpgData;\n';
  fn += 'static int jpgv_jpgDataPos;\n';
  fn += 'static int jpgv_jpgDataLen;\n';
  fn += 'static size_t jpgv_inFunc(JDEC*, uint8_t* buf, size_t n) {\n';
  fn += '  size_t avail = jpgv_jpgDataLen - jpgv_jpgDataPos;\n';
  fn += '  if (n > avail) n = avail;\n';
  fn += '  if (buf) memcpy(buf, jpgv_jpgData + jpgv_jpgDataPos, n);\n';
  fn += '  jpgv_jpgDataPos += n;\n';
  fn += '  return n;\n';
  fn += '}\n';
  fn += 'static uint16_t* jpgv_decBuf = nullptr;\n';
  fn += 'static uint16_t* jpgv_outTarget = nullptr;\n';
  fn += 'static int jpgv_decW = 0;\n';
  fn += 'static int jpgv_decH = 0;\n';
  fn += 'static int jpgv_storeOutFunc(JDEC*, void* bitmap, JRECT* rect) {\n';
  fn += '  int16_t rw = rect->right - rect->left + 1;\n';
  fn += '  int16_t rh = rect->bottom - rect->top + 1;\n';
  fn += '  uint16_t* bmp = (uint16_t*)bitmap;\n';
  fn += '  int16_t left = rect->left;\n';
  fn += '  if (left >= jpgv_decW) return 1;\n';
  fn += '  if (left + rw > jpgv_decW) rw = jpgv_decW - left;\n';
  fn += '  for (int y = 0; y < rh; y++) {\n';
  fn += '    int dy = rect->top + y;\n';
  fn += '    if (dy >= jpgv_decH) continue;\n';
  fn += '    memcpy(&jpgv_outTarget[dy * jpgv_decW + left], &bmp[y * rw], rw * 2);\n';
  fn += '  }\n';
  fn += '  return 1;\n';
  fn += '}\n';
  fn += 'bool jpgvLastDecodeDegraded = false;\n';
  fn += 'bool espJpegDecode565(const uint8_t* jpgData, uint32_t jpgLen, int maxW, uint16_t*& outBuf, int& outW, int& outH, uint8_t _swap) {\n';
  fn += '  bool isProg = false;\n';
  fn += '  for (uint32_t ii = 2; ii + 4 < jpgLen && ii < 8192; ) {\n';
  fn += '    if (jpgData[ii] != 0xFF) { ii++; continue; }\n';
  fn += '    uint8_t mm = jpgData[ii+1];\n';
  fn += '    if (mm == 0xFF) { ii++; continue; }\n';
  fn += '    if (mm == 0xDA) break;\n';
  fn += '    if (mm == 0xC2) { isProg = true; break; }\n';
  fn += '    if (mm == 0xD8 || mm == 0xD9 || (mm >= 0xD0 && mm <= 0xD7)) { ii += 2; continue; }\n';
  fn += '    if (ii + 4 >= jpgLen) break;\n';
  fn += '    uint16_t ssl = (jpgData[ii+2] << 8) | jpgData[ii+3];\n';
  fn += '    ii += 2 + ssl;\n';
  fn += '  }\n';
  fn += '  for (int tryW = maxW; tryW >= 80; tryW /= 2) {\n';
  fn += '  if (isProg) {\n';
  fn += '    uint16_t* pBuf = nullptr; int pW = 0, pH = 0;\n';
  fn += '    if (decodeProgJpegFull((uint8_t*)jpgData, (int)jpgLen, tryW, &pBuf, &pW, &pH)) {\n';
  fn += '      outBuf = pBuf; outW = pW; outH = pH;\n';
  fn += '      return true;\n';
  fn += '    }\n';
  fn += '    Serial.printf("[JPGV] prog full decode failed (tryW=%d), fallback\\n", tryW);\n';
  fn += '    if (tryW > 320) {\n';
  fn += '      uint16_t* pBuf2 = nullptr; int pW2 = 0, pH2 = 0;\n';
  fn += '      if (decodeProgJpegFull((uint8_t*)jpgData, (int)jpgLen, 320, &pBuf2, &pW2, &pH2)) { outBuf = pBuf2; outW = pW2; outH = pH2; return true; }\n';
  fn += '    }\n';
  fn += '    jpgvLastDecodeDegraded = true;\n';
  fn += '  }\n';
  fn += '  JDEC jdec;\n';
  fn += '  uint8_t* work = (uint8_t*)ps_malloc(TJPGD_WORKSPACE_SIZE);\n';
  fn += '  if (!work) { Serial.printf("[JPGV] workspace alloc fail\\n"); return false; }\n';
  fn += '  jpgv_jpgData = jpgData; jpgv_jpgDataPos = 0; jpgv_jpgDataLen = jpgLen;\n';
  fn += '  JRESULT r = jd_prepare(&jdec, jpgv_inFunc, work, TJPGD_WORKSPACE_SIZE, nullptr);\n';
  fn += '  if (r != JDR_OK) { Serial.printf("[JPGV] prep=%d w=%d h=%d p=%d msx=%d msy=%d\\n", (int)r, jdec.width, jdec.height, jdec.progressive, jdec.msx, jdec.msy); free(work); return false; }\n';
  fn += '  int srcW = jdec.width, srcH = jdec.height;\n';
  fn += '  uint8_t scale = 0;\n';
  fn += '  long psBudget = (long)ESP.getFreePsram() - 262144L;\n';
  fn += '  if (psBudget < 131072L) psBudget = 131072L;\n';
  fn += '  while (scale < 3) {\n';
  fn += '    long need = (long)(srcW >> scale) * (long)(srcH >> scale) * 2;\n';
  fn += '    if ((srcW >> scale) <= 960 && need <= psBudget) break;\n';
  fn += '    scale++;\n';
  fn += '  }\n';
  fn += '  Serial.printf("[JPGV] scale=%d need=%ld budget=%ld free=%u\\n", (int)scale, (long)(srcW >> scale) * (srcH >> scale) * 2, psBudget, (unsigned)ESP.getFreePsram());\n';
  fn += '  if (jdec.progressive) scale = 3;\n';
  fn += '  outW = srcW >> scale; outH = srcH >> scale;\n';
  fn += '  outBuf = nullptr;\n';
  fn += '  outBuf = (uint16_t*)ps_malloc((size_t)outW * outH * 2);\n';
  fn += '  if (!outBuf) { Serial.printf("[JPGV] decBuf alloc fail %dx%d (tryW=%d), shrink\\n", outW, outH, tryW); free(work); jpgvLastDecodeDegraded = true; continue; }\n';
  fn += '  memset(outBuf, 0, (size_t)outW * outH * 2);\n';
  fn += '  jpgv_outTarget = outBuf; jpgv_decW = outW; jpgv_decH = outH;\n';
  fn += '  jdec.swap = _swap;\n';
  fn += '  JRESULT r2 = jd_decomp(&jdec, jpgv_storeOutFunc, scale);\n';
  fn += '  if (r2 != JDR_OK) { Serial.printf("[JPGV] decomp fail=%d\\n", (int)r2); free(outBuf); outBuf = nullptr; jpgv_outTarget = nullptr; }\n';
  fn += '  free(work);\n';
  fn += '  if (r2 != JDR_OK) return false;\n';
  fn += '  Serial.printf("[JPGV] dec %dx%d scale=%d tryW=%d prog=%d\\n", outW, outH, (int)scale, tryW, (int)jdec.progressive);\n';
  fn += '  if (jdec.progressive) jpgvLastDecodeDegraded = true;\n';
  fn += '  return true;\n';
  fn += '  }\n';
  fn += '  Serial.printf("[JPGV] all decode attempts failed\\n");\n';
  fn += '  return false;\n';
  fn += '}\n';
  fn += 'static int jpgv_readWhole(File& f, const String& path, uint8_t* fileBuf, int sz) {\n';
  fn += '  int rd = 0;\n';
  fn += '  int stallCount = 0;\n';
  fn += '  while (rd < sz) {\n';
  fn += '    int want = sz - rd; if (want > 8192) want = 8192;\n';
  fn += '    int n = f.read(fileBuf + rd, want);\n';
  fn += '    if (n <= 0) {\n';
  fn += '      Serial.printf("[JPGV] stall at %d/%d #%d\\n", rd, sz, stallCount);\n';
  fn += '      f.close(); delay(100); sdfatReinit();\n';
  fn += '      f = SD.open(path, FILE_READ);\n';
  fn += '      if (!f) { if (++stallCount > 5) break; delay(200); continue; }\n';
  fn += '      f.seek(rd);\n';
  fn += '      if (++stallCount > 10) break;\n';
  fn += '      continue;\n';
  fn += '    }\n';
  fn += '    rd += n; stallCount = 0;\n';
  fn += '  }\n';
  fn += '  return rd;\n';
  fn += '}\n';
  fn += 'typedef struct { File f; const char* path; uint32_t pos; uint32_t total; int stalls; } jpgvFileSrc;\n';
  fn += 'static size_t jpgv_fileInFunc(JDEC* jd, uint8_t* buf, size_t n) {\n';
  fn += '  jpgvFileSrc* s = (jpgvFileSrc*)jd->device;\n';
  fn += '  if (buf == NULL) { s->pos += (uint32_t)n; if (s->f) s->f.seek(s->pos); return n; }\n';
  fn += '  size_t got = 0;\n';
  fn += '  while (got < n) {\n';
  fn += '    int r = 0;\n';
  fn += '    if (s->f) r = s->f.read(buf + got, n - got);\n';
  fn += '    if (r <= 0) {\n';
  fn += '      if (s->pos >= s->total) break;\n';
  fn += '      Serial.printf("[JPGV] stream stall at %u #%d\\n", (unsigned)s->pos, s->stalls);\n';
  fn += '      if (s->f) s->f.close();\n';
  fn += '      delay(100);\n';
  fn += '      if (++s->stalls > 6) break;\n';
  fn += '      sdfatReinit();\n';
  fn += '      s->f = SD.open(s->path, FILE_READ);\n';
  fn += '      if (!s->f) { delay(150); continue; }\n';
  fn += '      s->f.seek(s->pos);\n';
  fn += '      continue;\n';
  fn += '    }\n';
  fn += '    s->pos += (uint32_t)r; got += (size_t)r; s->stalls = 0;\n';
  fn += '  }\n';
  fn += '  return got;\n';
  fn += '}\n';
  fn += 'static bool espJpegDecode565File(File& f, const String& path, int maxW, uint16_t*& outBuf, int& outW, int& outH, uint8_t _swap, bool* isProg, bool fitMode, bool* wasScaled) {\n';
  fn += '  *isProg = false;\n';
  fn += '  *wasScaled = false;\n';
  fn += '  if (!f) return false;\n';
  fn += '  f.seek(0);\n';
  fn += '  jpgvFileSrc src; src.f = f; src.path = path.c_str(); src.pos = 0; src.total = f.size(); src.stalls = 0;\n';
  fn += '  uint8_t* work = (uint8_t*)ps_malloc(TJPGD_WORKSPACE_SIZE);\n';
  fn += '  if (!work) { Serial.printf("[JPGV] workspace alloc fail\\n"); src.f.close(); f.close(); return false; }\n';
  fn += '  JDEC jdec;\n';
  fn += '  JRESULT r = jd_prepare(&jdec, jpgv_fileInFunc, work, TJPGD_WORKSPACE_SIZE, &src);\n';
  fn += '  if (r != JDR_OK) { Serial.printf("[JPGV] prep(file)=%d\\n", (int)r); free(work); src.f.close(); f.close(); return false; }\n';
  fn += '  if (jdec.progressive) { *isProg = true; Serial.printf("[JPGV] progressive via stream, fallback to mem\\n"); free(work); src.f.close(); f.close(); return false; }\n';
  fn += '  int srcW = jdec.width, srcH = jdec.height;\n';
  fn += '  uint8_t scale = 0;\n';
  fn += '  long psBudget = (long)ESP.getFreePsram() - 262144L;\n';
  fn += '  if (psBudget < 131072L) psBudget = 131072L;\n';
  fn += '  if (fitMode) {\n';
  fn += '    while (scale < 3) {\n';
  fn += '      long needF = (long)(srcW >> scale) * (long)(srcH >> scale) * 2;\n';
  fn += '      if ((srcW >> scale) <= 960 && needF <= psBudget) break;\n';
  fn += '      scale++;\n';
  fn += '    }\n';
  fn += '  } else {\n';
  fn += '  while (scale < 3) {\n';
  fn += '    long need = (long)(srcW >> scale) * (long)(srcH >> scale) * 2;\n';
  fn += '    if ((srcW >> scale) <= 960 && need <= psBudget) break;\n';
  fn += '    scale++;\n';
  fn += '  }\n';
  fn += '  }\n';
  fn += '  Serial.printf("[JPGV] stream scale=%d need=%ld budget=%ld free=%u\\n", (int)scale, (long)(srcW >> scale) * (srcH >> scale) * 2, psBudget, (unsigned)ESP.getFreePsram());\n';
  fn += '  outW = srcW >> scale; outH = srcH >> scale;\n';
  fn += '  outBuf = (uint16_t*)ps_malloc((size_t)outW * outH * 2);\n';
  fn += '  if (!outBuf) { Serial.printf("[JPGV] stream decBuf alloc fail %dx%d\\n", outW, outH); free(work); src.f.close(); f.close(); return false; }\n';
  fn += '  memset(outBuf, 0, (size_t)outW * outH * 2);\n';
  fn += '  jpgv_outTarget = outBuf; jpgv_decW = outW; jpgv_decH = outH;\n';
  fn += '  jdec.swap = _swap;\n';
  fn += '  JRESULT r2 = jd_decomp(&jdec, jpgv_storeOutFunc, scale);\n';
  fn += '  free(work);\n';
  fn += '  src.f.close(); f.close();\n';
  fn += '  if (r2 != JDR_OK) { Serial.printf("[JPGV] stream decomp fail=%d\\n", (int)r2); free(outBuf); outBuf = nullptr; jpgv_outTarget = nullptr; return false; }\n';
  fn += '  Serial.printf("[JPGV] stream dec %dx%d scale=%d\\n", outW, outH, (int)scale);\n';
  fn += '  return true;\n';
  fn += '}\n';
  fn += 'extern void epubFontRelease() __attribute__((weak));\n';
  fn += 'extern void epubFontRestore() __attribute__((weak));\n';
  fn += 'static int jpgv_imgW = 0;\n';
  fn += 'static int jpgv_imgH = 0;\n';
  fn += 'static int jpgv_viewY = 0;\n';
  fn += 'static int jpgv_zoom = 0;\n';
  fn += 'static int jpgv_zoomX = 0;\n';
  fn += 'static int jpgv_zoomY = 0;\n';
  fn += 'static int jpgv_grid = 0;\n';
  fn += 'static int jpgv_gridCols = 0;\n';
  fn += 'static int jpgv_gridRows = 0;\n';
  fn += 'static int jpgv_cellIdx = 0;\n';
  fn += 'static int jpgv_gridRTL = 1;\n';
  fn += 'static int jpgv_rowsPerPage = 1;\n';
  fn += 'static int jpgv_keepZoom = 0;\n';
  fn += 'static bool jpgv_scaledDecode = false;\n';
  fn += 'static String jpgv_path;\n';
  fn += 'static int jpgv_spreadX = 0;\n';
  fn += 'static String jpgv_dirCache;\n';
  fn += 'static String* jpgv_fileList = nullptr;\n';
  fn += 'static int jpgv_fileCount = 0;\n';
  fn += 'static int jpgv_fileIdx = -1;\n';
  fn += 'static int jpgv_pages = 1;\n';
  fn += 'static int jpgv_pageIdx = 0;\n';
  fn += 'static int jpgv_pnX0 = 0;\n';
  fn += 'static int jpgv_pnW = 0;\n';
  fn += 'static void jpgv_pageWindow() {\n';
  fn += '  if (jpgv_pages < 2) { jpgv_pnX0 = 0; jpgv_pnW = jpgv_imgW; return; }\n';
  fn += '  bool firstPhysLeft = !jpgv_gridRTL;\n';
  fn += '  bool wantLeft = (jpgv_pageIdx == 0) ? firstPhysLeft : !firstPhysLeft;\n';
  fn += '  if (wantLeft) { jpgv_pnX0 = 0; jpgv_pnW = jpgv_spreadX; }\n';
  fn += '  else { jpgv_pnX0 = jpgv_spreadX; jpgv_pnW = jpgv_imgW - jpgv_spreadX; }\n';
  fn += '  if (jpgv_pnW < 1) { jpgv_pnX0 = 0; jpgv_pnW = jpgv_imgW; }\n';
  fn += '}\n';
  fn += 'static void jpgv_calcPage() {\n';
  fn += '  jpgv_pageWindow();\n';
  fn += '  jpgv_trimPageH();\n';
  fn += '  if (jpgv_pages == 2 && jpgv_pnW < jpgv_imgW / 8) {\n';
  fn += '    jpgv_pageIdx = 1 - jpgv_pageIdx;\n';
  fn += '    jpgv_pageWindow();\n';
  fn += '    jpgv_trimPageH();\n';
  fn += '  }\n';
  fn += '  int scrW = tft.width();\n';
  fn += '  jpgv_rowsPerPage = (int)((long)tft.height() * jpgv_pnW / scrW);\n';
  fn += '  if (jpgv_rowsPerPage < 1) jpgv_rowsPerPage = 1;\n';
  fn += '}\n';
  fn += 'static int jpgv_lum(uint16_t q) { uint16_t v = (uint16_t)((q >> 8) | (q << 8)); return ((v >> 11) & 0x1F) + ((v >> 5) & 0x3F) + (v & 0x1F); }\n';
  fn += 'static int jpgv_rowDark(int y, int st) {\n';
  fn += '  if (!jpgv_decBuf || y < 0 || y >= jpgv_imgH || jpgv_pnW <= 0) return 1 << 20;\n';
  fn += '  const uint16_t* r = &jpgv_decBuf[(size_t)y * jpgv_imgW];\n';
  fn += '  if (st < 1) st = 1;\n';
  fn += '  long d = 0; int n = 0;\n';
  fn += '  int x1 = jpgv_pnX0 + jpgv_pnW;\n';
  fn += '  for (int x = jpgv_pnX0; x < x1; x += st) { d += jpgv_lum(r[x]); n++; }\n';
  fn += '  return n ? (int)(d / n) : (1 << 20);\n';
  fn += '}\n';
  fn += 'static int jpgv_inkThr = 8;\n';
  fn += 'static int jpgv_minLum = 0;\n';
  fn += 'static void jpgv_calcInkThr() {\n';
  fn += '  jpgv_minLum = 125;\n';
  fn += '  if (!jpgv_decBuf || jpgv_imgW <= 0 || jpgv_imgH <= 0) { jpgv_inkThr = 8; return; }\n';
  fn += '  int st = ((jpgv_imgW > jpgv_imgH) ? jpgv_imgW : jpgv_imgH) / 240 + 1;\n';
  fn += '  long s = 0; int n = 0;\n';
  fn += '  for (int y = 0; y < jpgv_imgH; y += st)\n';
  fn += '    for (int x = 0; x < jpgv_imgW; x += st) { int lv = jpgv_lum(jpgv_decBuf[(size_t)y * jpgv_imgW + x]); s += lv; n++; if (lv < jpgv_minLum) jpgv_minLum = lv; }\n';
  fn += '  int mean = n ? (int)(s / n) : 24;\n';
  fn += '  jpgv_inkThr = mean / 2; if (jpgv_inkThr < 2) jpgv_inkThr = 2;\n';
  fn += '}\n';
  fn += 'static int jpgv_bgLum = 120;  // 本页纸底亮度估计(lum制0~125;脏白纸~85-120,纯白~122)\n';
  fn += 'static void jpgv_calcBg() {\n';
  fn += '  jpgv_bgLum = 120;\n';
  fn += '  if (!jpgv_decBuf || jpgv_imgW < 16 || jpgv_imgH < 16) return;\n';
  fn += '  int hist[17] = {0}; long n = 0;\n';
  fn += '  int stx = jpgv_imgW / 24 + 1, sty = jpgv_imgH / 24 + 1;\n';
  fn += '  for (int x = 0; x < jpgv_imgW; x += stx) {\n';
  fn += '    for (int k = 0; k < 6; k++) { hist[jpgv_lum(jpgv_decBuf[(size_t)k * jpgv_imgW + x]) >> 3]++; n++; }\n';
  fn += '    for (int k = 0; k < 6; k++) { int y = jpgv_imgH - 1 - k; hist[jpgv_lum(jpgv_decBuf[(size_t)y * jpgv_imgW + x]) >> 3]++; n++; }\n';
  fn += '  }\n';
  fn += '  for (int y = 0; y < jpgv_imgH; y += sty) {\n';
  fn += '    for (int k = 0; k < 6; k++) { hist[jpgv_lum(jpgv_decBuf[(size_t)y * jpgv_imgW + k]) >> 3]++; n++; }\n';
  fn += '    for (int k = 0; k < 6; k++) { int x = jpgv_imgW - 1 - k; hist[jpgv_lum(jpgv_decBuf[(size_t)y * jpgv_imgW + x]) >> 3]++; n++; }\n';
  fn += '  }\n';
  fn += '  long acc = 0; int med = 120;\n';
  fn += '  for (int i = 0; i < 17; i++) { acc += hist[i]; if (acc >= n / 2) { med = i * 8 + 4; break; } }\n';
  fn += '  if (med >= 78) jpgv_bgLum = med;  // 纸底须够亮(≈160/255)；满幅暗图(边带=内容)不启用自适应裁边\n';
  fn += '}\n';
  fn += '// 纸判定: 均值接近本页纸底 且 墨点占比<=4%(容忍扫描脏点;旧算法 darkN<=1 一个脏点就漏裁)\n';
  fn += 'static bool jpgv_rowPaper(int y) {\n';
  fn += '  if (!jpgv_decBuf || y < 0 || y >= jpgv_imgH || jpgv_bgLum < 78) return false;\n';
  fn += '  int st = jpgv_imgW / 160 + 1;\n';
  fn += '  const uint16_t* r = &jpgv_decBuf[(size_t)y * jpgv_imgW];\n';
  fn += '  long s = 0; int n = 0, ink = 0;\n';
  fn += '  for (int x = 0; x < jpgv_imgW; x += st) { int lv = jpgv_lum(r[x]); s += lv; n++; if (lv < jpgv_bgLum - 22) ink++; }\n';
  fn += '  return n && (int)(s / n) >= jpgv_bgLum - 14 && ink * 25 <= n;\n';
  fn += '}\n';
  fn += 'static bool jpgv_colPaper(int x) {\n';
  fn += '  if (!jpgv_decBuf || x < 0 || x >= jpgv_imgW || jpgv_bgLum < 78) return false;\n';
  fn += '  int st = jpgv_imgH / 160 + 1;\n';
  fn += '  long s = 0; int n = 0, ink = 0;\n';
  fn += '  for (int y = 0; y < jpgv_imgH; y += st) { int lv = jpgv_lum(jpgv_decBuf[(size_t)y * jpgv_imgW + x]); s += lv; n++; if (lv < jpgv_bgLum - 22) ink++; }\n';
  fn += '  return n && (int)(s / n) >= jpgv_bgLum - 14 && ink * 25 <= n;\n';
  fn += '}\n';
  fn += 'static void jpgv_despeckle() {\n';
  fn += '  if (!jpgv_decBuf || jpgv_imgW < 8 || jpgv_imgH < 8) return;\n';
  fn += '  // remove isolated dark dust on bright paper; screentone dots have dark neighbors and survive\n';
  fn += '  for (int y = 2; y < jpgv_imgH - 2; y++) {\n';
  fn += '    for (int x = 2; x < jpgv_imgW - 2; x++) {\n';
  fn += '      uint16_t q = jpgv_decBuf[(size_t)y * jpgv_imgW + x];\n';
  fn += '      if (jpgv_lum(q) >= 60) continue;\n';
  fn += '      bool ring = true;\n';
  fn += '      for (int dy = -1; dy <= 1 && ring; dy++)\n';
  fn += '        for (int dx = -1; dx <= 1; dx++) {\n';
  fn += '          if (!dx && !dy) continue;\n';
  fn += '          if (jpgv_lum(jpgv_decBuf[(size_t)(y + dy) * jpgv_imgW + (x + dx)]) < 80) { ring = false; break; }\n';
  fn += '        }\n';
  fn += '      if (!ring) continue;\n';
  fn += '      long s5 = 0; int n5 = 0;\n';
  fn += '      for (int yy = y - 2; yy <= y + 2; yy++)\n';
  fn += '        for (int xx = x - 2; xx <= x + 2; xx++) { s5 += jpgv_lum(jpgv_decBuf[(size_t)yy * jpgv_imgW + xx]); n5++; }\n';
  fn += '      if (s5 / n5 >= 100) jpgv_decBuf[(size_t)y * jpgv_imgW + x] = 0xFFFF;\n';
  fn += '    }\n';
  fn += '  }\n';
  fn += '}\n';
  fn += 'static void jpgv_bleach() {\n';
  fn += '  if (!jpgv_decBuf || jpgv_imgW < 8 || jpgv_imgH < 8) return;\n';
  fn += '  // per-channel white-point normalization: paper -> pure white, ink deepened\n';
  fn += '  int hr[32] = {0}; int hg[64] = {0}; int hb[32] = {0};\n';
  fn += '  long tot = 0;\n';
  fn += '  for (int y = 0; y < jpgv_imgH; y += 2)\n';
  fn += '    for (int x = 0; x < jpgv_imgW; x += 2) {\n';
  fn += '      uint16_t v = (uint16_t)((jpgv_decBuf[(size_t)y * jpgv_imgW + x] >> 8) | (jpgv_decBuf[(size_t)y * jpgv_imgW + x] << 8));\n';
  fn += '      hr[(v >> 11) & 0x1F]++; hg[(v >> 5) & 0x3F]++; hb[v & 0x1F]++; tot++;\n';
  fn += '    }\n';
  fn += '  long acc = 0, tgt = tot * 96 / 100;\n';
  fn += '  int r5 = 31;\n';
  fn += '  for (int i = 0; i < 32; i++) { acc += hr[i]; if (acc >= tgt) { r5 = (i + 1 < 32) ? i + 1 : 32; break; } }\n';
  fn += '  acc = 0;\n';
  fn += '  int g6 = 63;\n';
  fn += '  for (int i = 0; i < 64; i++) { acc += hg[i]; if (acc >= tgt) { g6 = (i + 1 < 64) ? i + 1 : 64; break; } }\n';
  fn += '  acc = 0;\n';
  fn += '  int b5 = 31;\n';
  fn += '  for (int i = 0; i < 32; i++) { acc += hb[i]; if (acc >= tgt) { b5 = (i + 1 < 32) ? i + 1 : 32; break; } }\n';
  fn += '  if (r5 >= 31 && g6 >= 63 && b5 >= 31) return;  // already pure white paper\n';
  fn += '  for (int y = 0; y < jpgv_imgH; y++)\n';
  fn += '    for (int x = 0; x < jpgv_imgW; x++) {\n';
  fn += '      uint16_t q = jpgv_decBuf[(size_t)y * jpgv_imgW + x];\n';
  fn += '      uint16_t v = (uint16_t)((q >> 8) | (q << 8));\n';
  fn += '      int r = (v >> 11) & 0x1F, g = (v >> 5) & 0x3F, b = v & 0x1F;\n';
  fn += '      r = (r * 31 + r5 - 1) / r5; if (r > 31) r = 31;\n';
  fn += '      g = (g * 63 + g6 - 1) / g6; if (g > 63) g = 63;\n';
  fn += '      b = (b * 31 + b5 - 1) / b5; if (b > 31) b = 31;\n';
  fn += '      uint16_t w = (uint16_t)((r << 11) | (g << 5) | b);\n';
  fn += '      jpgv_decBuf[(size_t)y * jpgv_imgW + x] = (uint16_t)((w >> 8) | (w << 8));\n';
  fn += '    }\n';
  fn += '}\n';
  fn += 'static int jpgv_rowDarkN(int y) {\n';
  fn += '  if (!jpgv_decBuf || y < 0 || y >= jpgv_imgH) return 0;\n';
  fn += '  int xst = jpgv_imgW / 160 + 1;\n';
  fn += '  const uint16_t* r = &jpgv_decBuf[(size_t)y * jpgv_imgW];\n';
  fn += '  int n = 0;\n';
  fn += '  for (int x = 0; x < jpgv_imgW; x += xst) if (jpgv_lum(r[x]) < jpgv_inkThr) n++;\n';
  fn += '  return n;\n';
  fn += '}\n';
  fn += 'static int jpgv_rowAvgLum(int y) {\n';
  fn += '  if (!jpgv_decBuf || y < 0 || y >= jpgv_imgH) return 0;\n';
  fn += '  int xst = jpgv_imgW / 160 + 1;\n';
  fn += '  const uint16_t* r = &jpgv_decBuf[(size_t)y * jpgv_imgW];\n';
  fn += '  long s = 0; int n = 0;\n';
  fn += '  for (int x = 0; x < jpgv_imgW; x += xst) { s += jpgv_lum(r[x]); n++; }\n';
  fn += '  return n ? (int)(s / n) : 0;\n';
  fn += '}\n';
  fn += '// 纸带行走器：沿纸推进；≤3行尘埃岛(其后≥10行纸)跳过；起始伪影带(≤skMax)允许；全程未见纸则不裁\n';
  fn += 'static int jpgv_walkPaperDown(int y, int yMax, int skMax) {\n';
  fn += '  int start = y; bool saw = false;\n';
  fn += '  while (y < yMax) {\n';
  fn += '    if (jpgv_rowPaper(y)) { saw = true; y++; continue; }\n';
  fn += '    int j = y;\n';
  fn += '    while (j < yMax && !jpgv_rowPaper(j) && j - y < 3) j++;\n';
  fn += '    if (j < yMax && jpgv_rowPaper(j)) {\n';
  fn += '      int k = j;\n';
  fn += '      while (k < yMax && jpgv_rowPaper(k) && k - j < 10) k++;\n';
  fn += '      if (k - j >= 10) { saw = true; y = k; continue; }\n';
  fn += '    }\n';
  fn += '    if (!saw && y - start < skMax) { y++; continue; }\n';
  fn += '    break;\n';
  fn += '  }\n';
  fn += '  return saw ? y : start;\n';
  fn += '}\n';
  fn += 'static int jpgv_walkPaperUp(int y, int yMin, int skMax) {\n';
  fn += '  int start = y; bool saw = false;\n';
  fn += '  while (y > yMin) {\n';
  fn += '    if (jpgv_rowPaper(y)) { saw = true; y--; continue; }\n';
  fn += '    int j = y;\n';
  fn += '    while (j > yMin && !jpgv_rowPaper(j) && y - j < 3) j--;\n';
  fn += '    if (j > yMin && jpgv_rowPaper(j)) {\n';
  fn += '      int k = j;\n';
  fn += '      while (k > yMin && jpgv_rowPaper(k) && j - k < 10) k--;\n';
  fn += '      if (j - k >= 10) { saw = true; y = k; continue; }\n';
  fn += '    }\n';
  fn += '    if (!saw && start - y < skMax) { y--; continue; }\n';
  fn += '    break;\n';
  fn += '  }\n';
  fn += '  return saw ? y : start;\n';
  fn += '}\n';
  fn += 'static int jpgv_walkPaperRight(int x, int xMax, int skMax) {\n';
  fn += '  int start = x; bool saw = false;\n';
  fn += '  while (x < xMax) {\n';
  fn += '    if (jpgv_colPaper(x)) { saw = true; x++; continue; }\n';
  fn += '    int j = x;\n';
  fn += '    while (j < xMax && !jpgv_colPaper(j) && j - x < 3) j++;\n';
  fn += '    if (j < xMax && jpgv_colPaper(j)) {\n';
  fn += '      int k = j;\n';
  fn += '      while (k < xMax && jpgv_colPaper(k) && k - j < 10) k++;\n';
  fn += '      if (k - j >= 10) { saw = true; x = k; continue; }\n';
  fn += '    }\n';
  fn += '    if (!saw && x - start < skMax) { x++; continue; }\n';
  fn += '    break;\n';
  fn += '  }\n';
  fn += '  return saw ? x : start;\n';
  fn += '}\n';
  fn += 'static int jpgv_walkPaperLeft(int x, int xMin, int skMax) {\n';
  fn += '  int start = x; bool saw = false;\n';
  fn += '  while (x > xMin) {\n';
  fn += '    if (jpgv_colPaper(x)) { saw = true; x--; continue; }\n';
  fn += '    int j = x;\n';
  fn += '    while (j > xMin && !jpgv_colPaper(j) && x - j < 3) j--;\n';
  fn += '    if (j > xMin && jpgv_colPaper(j)) {\n';
  fn += '      int k = j;\n';
  fn += '      while (k > xMin && jpgv_colPaper(k) && j - k < 10) k--;\n';
  fn += '      if (j - k >= 10) { saw = true; x = k; continue; }\n';
  fn += '    }\n';
  fn += '    if (!saw && start - x < skMax) { x--; continue; }\n';
  fn += '    break;\n';
  fn += '  }\n';
  fn += '  return saw ? x : start;\n';
  fn += '}\n';
  fn += 'static void jpgv_trimMarginsV() {\n';
  fn += '  if (!jpgv_decBuf || jpgv_imgH < 24) return;\n';
  fn += '  if (jpgv_minLum >= 90) return;  // blank page: keep as-is\n';
  fn += '  int cap = jpgv_imgH * 30 / 100; if (cap < 4) cap = 4;\n';
  fn += '  // cut only near-white paper rows: no ink and bright average\n';
  fn += '  int skMaxR = jpgv_imgH / 30; if (skMaxR < 8) skMaxR = 8;\n';
  fn += '  int yTop = jpgv_walkPaperDown(0, cap, skMaxR);\n';
  fn += '  int yBot = jpgv_walkPaperUp(jpgv_imgH - 1, jpgv_imgH - 1 - cap, skMaxR);\n';
  fn += '  if (yTop >= yBot) return;\n';
  fn += '  int pad = jpgv_imgH / 200 + 2;\n';
  fn += '  yTop -= pad; if (yTop < 0) yTop = 0;\n';
  fn += '  yBot += pad; if (yBot >= jpgv_imgH) yBot = jpgv_imgH - 1;\n';
  fn += '  int nh = yBot - yTop + 1;\n';
  fn += '  if (nh >= jpgv_imgH * 40 / 100 && (yTop > 0 || yBot < jpgv_imgH - 1)) {\n';
  fn += '    memmove(jpgv_decBuf, &jpgv_decBuf[(size_t)yTop * jpgv_imgW], (size_t)nh * jpgv_imgW * 2);\n';
  fn += '    jpgv_imgH = nh;\n';
  fn += '  }\n';
  fn += '}\n';
  fn += 'static int jpgv_colDarkN(int x) {\n';
  fn += '  if (!jpgv_decBuf || x < 0 || x >= jpgv_imgW) return 0;\n';
  fn += '  int yst = jpgv_imgH / 160 + 1;\n';
  fn += '  int n = 0;\n';
  fn += '  for (int y = 0; y < jpgv_imgH; y += yst) if (jpgv_lum(jpgv_decBuf[(size_t)y * jpgv_imgW + x]) < jpgv_inkThr) n++;\n';
  fn += '  return n;\n';
  fn += '}\n';
  fn += 'static int jpgv_colAvgLum(int x) {\n';
  fn += '  if (!jpgv_decBuf || x < 0 || x >= jpgv_imgW) return 999;\n';
  fn += '  int yst = jpgv_imgH / 160 + 1;\n';
  fn += '  long s = 0; int n = 0;\n';
  fn += '  for (int y = 0; y < jpgv_imgH; y += yst) { s += jpgv_lum(jpgv_decBuf[(size_t)y * jpgv_imgW + x]); n++; }\n';
  fn += '  return n ? (int)(s / n) : 999;\n';
  fn += '}\n';
  fn += 'static void jpgv_trimPageH() {\n';
  fn += '  if (!jpgv_decBuf || jpgv_pnW < 24) return;\n';
  fn += '  if (jpgv_minLum >= 90) return;  // blank page: keep as-is\n';
  fn += '  int cap = jpgv_pnW * 30 / 100; if (cap < 4) cap = 4;\n';
  fn += '  // cut only near-white paper columns: no ink and bright average\n';
  fn += '  int skMaxC = jpgv_pnW / 30; if (skMaxC < 8) skMaxC = 8;\n';
  fn += '  int xL = jpgv_walkPaperRight(jpgv_pnX0, jpgv_pnX0 + cap, skMaxC);\n';
  fn += '  int xR = jpgv_walkPaperLeft(jpgv_pnX0 + jpgv_pnW - 1, jpgv_pnX0 + jpgv_pnW - 1 - cap, skMaxC);\n';
  fn += '  if (xL >= xR) return;\n';
  fn += '  int pad = jpgv_pnW / 200 + 2;\n';
  fn += '  xL -= pad; if (xL < jpgv_pnX0) xL = jpgv_pnX0;\n';
  fn += '  xR += pad; if (xR >= jpgv_pnX0 + jpgv_pnW) xR = jpgv_pnX0 + jpgv_pnW - 1;\n';
  fn += '  int nw = xR - xL + 1;\n';
  fn += '  if (nw >= jpgv_pnW * 40 / 100) { jpgv_pnX0 = xL; jpgv_pnW = nw; }\n';
  fn += '  if (jpgv_pnW < 1) jpgv_pnW = 1;\n';
  fn += '}\n';

  // Left gutter crop for manga scans (removes book-binding spine white edge)
  fn += 'static int jpgv_gutterL = 0;\n';
  fn += 'static void jpgv_trimGutter() {\n';
  fn += '  jpgv_gutterL = 0;\n';
  fn += '  if (!jpgv_decBuf || jpgv_imgW < 40 || jpgv_imgH < 40) return;\n';
  fn += '  int yStep = jpgv_imgH / 120 + 1;\n';
  fn += '  // Pass 1: wide scan for obvious white gutter (up to imgW/3, max 120px)\n';
  fn += '  int scanW1 = jpgv_imgW / 3; if (scanW1 > 120) scanW1 = 120; if (scanW1 < 10) scanW1 = 10;\n';
  fn += '  long brightSum = 0; int brightN = 0;\n';
  fn += '  for (int x = 0; x < scanW1; x++) {\n';
  fn += '    long colSum = 0; int colN = 0;\n';
  fn += '    for (int y = 0; y < jpgv_imgH; y += yStep) { colSum += jpgv_lum(jpgv_decBuf[(size_t)y * jpgv_imgW + x]); colN++; }\n';
  fn += '    if (colN > 0) { brightSum += colSum / colN; brightN++; }\n';
  fn += '  }\n';
  fn += '  if (brightN == 0) return;\n';
  fn += '  int avgBright = (int)(brightSum / brightN);\n';
  fn += '  if (avgBright < 90) return;  // left region not white paper: normal image, do not crop\n';
  fn += '  int thr = avgBright * 11 / 10; if (thr < 60) thr = 60; if (thr > 200) thr = 200;\n';
  fn += '  int cutX = 0;\n';
  fn += '  for (int x = 1; x < scanW1 && x < jpgv_imgW - 4; x++) {\n';
  fn += '    long cs = 0; int cn = 0;\n';
  fn += '    for (int y = 0; y < jpgv_imgH; y += yStep) { cs += jpgv_lum(jpgv_decBuf[(size_t)y * jpgv_imgW + x]); cn++; }\n';
  fn += '    int avg = cn ? (int)(cs / cn) : 999;\n';
  fn += '    if (avg < thr) { cutX = x; break; }\n';
  fn += '  }\n';
  fn += '  if (cutX >= 2) {\n';
  fn += '    int gutCols = 0;\n';
  fn += '    for (int x = 0; x < cutX; x++) {\n';
  fn += '      long cs = 0; int cn = 0;\n';
  fn += '      for (int y = 0; y < jpgv_imgH; y += yStep) { cs += jpgv_lum(jpgv_decBuf[(size_t)y * jpgv_imgW + x]); cn++; }\n';
  fn += '      if (cn && (int)(cs / cn) >= thr * 80 / 100) gutCols++;\n';
  fn += '    }\n';
  fn += '    if (gutCols * 2 >= cutX) {\n';
  fn += '      int nw1 = jpgv_imgW - cutX;\n';
  fn += '      for (int y = 0; y < jpgv_imgH; y++) {\n';
  fn += '        memmove(&jpgv_decBuf[(size_t)y * nw1], &jpgv_decBuf[(size_t)y * jpgv_imgW + cutX], (size_t)nw1 * 2);\n';
  fn += '      }\n';
  fn += '      jpgv_imgW = nw1;\n';
  fn += '      jpgv_gutterL = cutX;\n';
  fn += '    }\n';
  fn += '  }\n';
  fn += '  // Pass 2: tight scan for remaining thin white edge (up to 15px)\n';
  fn += '  int scanW2 = 15; if (scanW2 >= jpgv_imgW) scanW2 = jpgv_imgW - 1;\n';
  fn += '  brightSum = 0; brightN = 0;\n';
  fn += '  for (int x = 0; x < scanW2; x++) {\n';
  fn += '    long colSum = 0; int colN = 0;\n';
  fn += '    for (int y = 0; y < jpgv_imgH; y += yStep) { colSum += jpgv_lum(jpgv_decBuf[(size_t)y * jpgv_imgW + x]); colN++; }\n';
  fn += '    if (colN > 0) { brightSum += colSum / colN; brightN++; }\n';
  fn += '  }\n';
  fn += '  if (brightN == 0) return;\n';
  fn += '  avgBright = (int)(brightSum / brightN);\n';
  fn += '  if (avgBright < 90) return;  // thin edge region not white: skip\n';
  fn += '  thr = avgBright * 11 / 10; if (thr < 50) thr = 50; if (thr > 180) thr = 180;\n';
  fn += '  cutX = 0;\n';
  fn += '  for (int x = 1; x < scanW2 && x < jpgv_imgW - 2; x++) {\n';
  fn += '    long cs = 0; int cn = 0;\n';
  fn += '    for (int y = 0; y < jpgv_imgH; y += yStep) { cs += jpgv_lum(jpgv_decBuf[(size_t)y * jpgv_imgW + x]); cn++; }\n';
  fn += '    int avg = cn ? (int)(cs / cn) : 999;\n';
  fn += '    if (avg < thr) { cutX = x; break; }\n';
  fn += '  }\n';
  fn += '  if (cutX >= 2) {\n';
  fn += '    int gutCols = 0;\n';
  fn += '    for (int x = 0; x < cutX; x++) {\n';
  fn += '      long cs = 0; int cn = 0;\n';
  fn += '      for (int y = 0; y < jpgv_imgH; y += yStep) { cs += jpgv_lum(jpgv_decBuf[(size_t)y * jpgv_imgW + x]); cn++; }\n';
  fn += '      if (cn && (int)(cs / cn) >= thr * 80 / 100) gutCols++;\n';
  fn += '    }\n';
  fn += '    if (gutCols * 2 >= cutX) {\n';
  fn += '      int nw2 = jpgv_imgW - cutX;\n';
  fn += '      for (int y = 0; y < jpgv_imgH; y++) {\n';
  fn += '        memmove(&jpgv_decBuf[(size_t)y * nw2], &jpgv_decBuf[(size_t)y * jpgv_imgW + cutX], (size_t)nw2 * 2);\n';
  fn += '      }\n';
  fn += '      jpgv_imgW = nw2;\n';
  fn += '      jpgv_gutterL += cutX;\n';
  fn += '    }\n';
  fn += '  }\n';
  fn += '}\n';
  fn += 'static void jpgv_findSpread() {\n';
  fn += '  jpgv_spreadX = 0; jpgv_pages = 1;\n';
  fn += '  if (jpgv_imgW <= jpgv_imgH || !jpgv_decBuf) return;\n';
  fn += '  int b0 = jpgv_imgW / 2 - jpgv_imgW / 4;\n';
  fn += '  int b1 = jpgv_imgW / 2 + jpgv_imgW / 4;\n';
  fn += '  if (b0 < 4) b0 = 4;\n';
  fn += '  if (b1 > jpgv_imgW - 4) b1 = jpgv_imgW - 4;\n';
  fn += '  int rst = (jpgv_imgH / 200) + 1;\n';
  fn += '  long best = -1; int bx = 0;\n';
  fn += '  for (int x = b0; x <= b1; x++) {\n';
  fn += '    long d = 0; int n = 0;\n';
  fn += '    for (int y = 0; y < jpgv_imgH; y += rst) { d += jpgv_lum(jpgv_decBuf[(size_t)y * jpgv_imgW + x]); n++; }\n';
  fn += '    int avg = n ? (int)(d / n) : 999;\n';
  fn += '    if (best < 0 || avg < best) { best = avg; bx = x; }\n';
  fn += '  }\n';
  fn += '  long edge = 0; int en = 0;\n';
  fn += '  for (int y = 0; y < jpgv_imgH; y += rst) {\n';
  fn += '    edge += jpgv_lum(jpgv_decBuf[(size_t)y * jpgv_imgW + 2]);\n';
  fn += '    edge += jpgv_lum(jpgv_decBuf[(size_t)y * jpgv_imgW + jpgv_imgW - 3]);\n';
  fn += '    en += 2;\n';
  fn += '  }\n';
  fn += '  int edgeAvg = en ? (int)(edge / en) : 999;\n';
  fn += '  int lw = bx, rw = jpgv_imgW - bx;\n';
  fn += '  if (best >= 0 && best < 34 && edgeAvg > 60 && best < edgeAvg * 45 / 100\n';
  fn += '      && lw > jpgv_imgW / 8 && rw > jpgv_imgW / 8) {\n';
  fn += '    jpgv_spreadX = bx; jpgv_pages = 2;\n';
  fn += '    int scrW = tft.width(), scrH = tft.height();\n';
  fn += '    long wholeH = (long)jpgv_imgH * scrW / jpgv_imgW;\n';
  fn += '    if (jpgv_imgW <= scrW * 2 && wholeH <= (long)scrH) { jpgv_spreadX = 0; jpgv_pages = 1; }\n';
  fn += '  }\n';
  fn += '}\n';
  fn += 'static int jpgv_snapStop(int y) {\n';
  fn += '  if (!jpgv_decBuf || jpgv_pnW <= 0) return y;\n';
  fn += '  int m = jpgv_rowsPerPage / 8; if (m < 1) m = 1;\n';
  fn += '  int y0 = y - m; if (y0 < 0) y0 = 0;\n';
  fn += '  int y1 = y + m; if (y1 >= jpgv_imgH) y1 = jpgv_imgH - 1;\n';
  fn += '  int st = (jpgv_pnW / 100) + 1;\n';
  fn += '  int bestY = y; long best = -1;\n';
  fn += '  for (int yy = y0; yy <= y1; yy++) {\n';
  fn += '    int d = jpgv_rowDark(yy, st);\n';
  fn += '    if (best < 0 || d < best) { best = d; bestY = yy; }\n';
  fn += '  }\n';
  fn += '  return bestY;\n';
  fn += '}\n';
  fn += 'static void jpgv_renderView() {\n';
  fn += '  int scrW = tft.width();\n';
  fn += '  int scrH = tft.height();\n';
  fn += '  static uint16_t* frm = nullptr;\n';
  fn += '  if (!frm) frm = (uint16_t*)ps_malloc((size_t)scrW * scrH * 2);\n';
  fn += '  if (frm && jpgv_decBuf && jpgv_imgW > 0) {\n';
  fn += '    if (jpgv_zoom) {\n';
  fn += '      int minX = jpgv_pnX0;\n';
  fn += '      int maxX = jpgv_pnX0 + jpgv_pnW - scrW; if (maxX < minX) maxX = minX;\n';
  fn += '      int maxY = jpgv_imgH - scrH; if (maxY < 0) maxY = 0;\n';
  fn += '      if (jpgv_zoomX > maxX) jpgv_zoomX = maxX; if (jpgv_zoomX < minX) jpgv_zoomX = minX;\n';
  fn += '      if (jpgv_zoomY > maxY) jpgv_zoomY = maxY; if (jpgv_zoomY < 0) jpgv_zoomY = 0;\n';
  fn += '      for (int y = 0; y < scrH; y++) {\n';
  fn += '        uint16_t* drow = &frm[(size_t)y * scrW];\n';
  fn += '        int sy = jpgv_zoomY + y;\n';
  fn += '        if (sy >= jpgv_imgH) { for (int x = 0; x < scrW; x++) drow[x] = 0; continue; }\n';
  fn += '        const uint16_t* srow = &jpgv_decBuf[(size_t)sy * jpgv_imgW];\n';
  fn += '        for (int x = 0; x < scrW; x++) { int sx = jpgv_zoomX + x; drow[x] = (sx >= jpgv_pnX0 && sx < jpgv_pnX0 + jpgv_pnW) ? srow[sx] : 0; }\n';
  fn += '      }\n';
  fn += '    } else {\n';
  fn += '      int maxY = jpgv_imgH - jpgv_rowsPerPage; if (maxY < 0) maxY = 0;\n';
  fn += '      if (jpgv_viewY > maxY) jpgv_viewY = maxY; if (jpgv_viewY < 0) jpgv_viewY = 0;\n';
  fn += '      for (int y = 0; y < scrH; y++) {\n';
  fn += '        uint16_t* drow = &frm[(size_t)y * scrW];\n';
  fn += '        int y0 = jpgv_viewY + (int)((long)y * jpgv_rowsPerPage / scrH);\n';
  fn += '        int y1 = jpgv_viewY + (int)((long)(y + 1) * jpgv_rowsPerPage / scrH);\n';
  fn += '        if (y1 >= jpgv_imgH) y1 = jpgv_imgH - 1;\n';
  fn += '        if (y1 < y0) y1 = y0;\n';
  fn += '        const uint16_t* srow = &jpgv_decBuf[(size_t)y0 * jpgv_imgW];\n';
  fn += '        const uint16_t* srow2 = (y1 > y0) ? &jpgv_decBuf[(size_t)y1 * jpgv_imgW] : srow;\n';
  fn += '        for (int x = 0; x < scrW; x++) {\n';
  fn += '          int x0 = jpgv_pnX0 + (int)((long)x * jpgv_pnW / scrW);\n';
  fn += '          int x1 = jpgv_pnX0 + (int)((long)(x + 1) * jpgv_pnW / scrW);\n';
  fn += '          if (x1 >= jpgv_pnX0 + jpgv_pnW) x1 = jpgv_pnX0 + jpgv_pnW - 1;\n';
  fn += '          if (x1 < x0) x1 = x0;\n';
  fn += '          uint32_t r = 0, g = 0, b = 0, n = 0;\n';
  fn += '          for (int yy = y0; yy <= y1; yy++) {\n';
  fn += '            const uint16_t* rr = (yy == y0) ? srow : ((yy == y1) ? srow2 : &jpgv_decBuf[(size_t)yy * jpgv_imgW]);\n';
  fn += '            for (int xx = x0; xx <= x1; xx++) { uint16_t q = (uint16_t)((rr[xx] >> 8) | (rr[xx] << 8)); r += (q >> 11) & 0x1F; g += (q >> 5) & 0x3F; b += q & 0x1F; n++; }\n';
  fn += '          }\n';
  fn += '          if (n) { uint16_t v = (uint16_t)(((r / n) << 11) | ((g / n) << 5) | (b / n)); drow[x] = (uint16_t)((v >> 8) | (v << 8)); }\n';
  fn += '        }\n';
  fn += '      }\n';
  fn += '    }\n';
  fn += '    tft.pushImage(0, 0, scrW, scrH, frm);\n';
  fn += '  } else {\n';
  fn += '    tft.fillRect(0, 0, scrW, scrH, TFT_BLACK);\n';
  fn += '  }\n';
  fn += '  if (jpgv_zoom) {\n';
  fn += '    tft.fillRoundRect(4, scrH - 20, 34, 17, 4, 0x0000);\n';
  fn += '    tft.drawRoundRect(4, scrH - 20, 34, 17, 4, 0x07E0);\n';
  fn += '    tft.setTextColor(0x07E0, 0x0000); tft.setTextSize(1); tft.setCursor(10, scrH - 16); tft.print(jpgv_grid ? (jpgv_gridRTL ? "G<" : "G>") : "1:1");\n';
  fn += '    if (jpgv_grid && jpgv_gridCols > 0 && jpgv_gridRows > 0 && jpgv_decBuf) {\n';
  fn += '      int mw = 32, mh = mw * scrH / scrW; if (mh < 22) { mh = 22; mw = mh * scrW / scrH; }\n';
  fn += '      int mx = scrW - mw - 6, my = scrH - mh - 6;\n';
  fn += '      tft.fillRoundRect(mx - 4, my - 2, mw + 8, mh + 8, 5, 0x0000);\n';
  fn += '      static uint16_t* thumbBuf = nullptr;\n';
  fn += '      if (!thumbBuf) thumbBuf = (uint16_t*)ps_malloc(64 * 64 * 2);\n';
  fn += '      if (thumbBuf) {\n';
  fn += '        for (int ty = 0; ty < mh; ty++) {\n';
  fn += '          int sy = ty * jpgv_imgH / mh; if (sy >= jpgv_imgH) sy = jpgv_imgH - 1;\n';
  fn += '          const uint16_t* srow = &jpgv_decBuf[(size_t)sy * jpgv_imgW];\n';
  fn += '          uint16_t* drow = &thumbBuf[ty * mw];\n';
  fn += '          for (int tx = 0; tx < mw; tx++) { int sx = jpgv_pnX0 + tx * jpgv_pnW / mw; if (sx >= jpgv_pnX0 + jpgv_pnW) sx = jpgv_pnX0 + jpgv_pnW - 1; drow[tx] = srow[sx]; }\n';
  fn += '        }\n';
  fn += '        tft.pushImage(mx, my, mw, mh, thumbBuf);\n';
  fn += '      } else { tft.fillRect(mx, my, mw, mh, 0x0000); }\n';
  fn += '      tft.drawRoundRect(mx - 3, my - 3, mw + 6, mh + 6, 4, 0x57EA);\n';
  fn += '      for (int r = 1; r < jpgv_gridRows; r++) { int yy = my + r * mh / jpgv_gridRows; tft.drawFastHLine(mx, yy, mw, 0x1A83); }\n';
  fn += '      for (int c = 1; c < jpgv_gridCols; c++) { int xx = mx + c * mw / jpgv_gridCols; tft.drawFastVLine(xx, my, mh, 0x1A83); }\n';
  fn += '      int cr = jpgv_cellIdx / jpgv_gridCols, cc = jpgv_cellIdx % jpgv_gridCols;\n';
  fn += '      if (jpgv_gridRTL) cc = jpgv_gridCols - 1 - cc;\n';
  fn += '      int cx = mx + cc * mw / jpgv_gridCols, cy = my + cr * mh / jpgv_gridRows;\n';
  fn += '      int cw = mw / jpgv_gridCols, ch = mh / jpgv_gridRows;\n';
  fn += '      tft.fillRoundRect(cx + 1, cy + 1, cw - 2, ch - 2, 2, 0x5800);\n';
  fn += '      tft.drawRoundRect(cx + 1, cy + 1, cw - 2, ch - 2, 2, 0xFDA0);\n';
  fn += '    }\n';
  fn += '  }\n';
  fn += '  { int sl = jpgv_path.lastIndexOf("/"); String fn0 = (sl >= 0) ? jpgv_path.substring(sl + 1) : jpgv_path;\n';
  fn += '    tft.setTextSize(1); int tw = tft.textWidth(fn0);\n';
  fn += '    tft.fillRoundRect((scrW - tw - 14) / 2, scrH - 20, tw + 14, 17, 4, 0x0000);\n';
  fn += '    tft.drawRoundRect((scrW - tw - 14) / 2, scrH - 20, tw + 14, 17, 4, 0x2AE5);\n';
  fn += '    tft.setTextColor(0x57EA, 0x0000); tft.setCursor((scrW - tw) / 2, scrH - 16); tft.print(fn0);\n';
  fn += '  }\n';
  fn += '}\n';
  fn += 'static int jpgv_stops[64];\n';
  fn += 'static int jpgv_stopCount = 0;\n';
  fn += 'static int jpgv_stopIdx = 0;\n';
  fn += 'static void jpgv_computeStops(int totalH, int scrH) {\n';
  fn += '  jpgv_stopCount = 0;\n';
  fn += '  if (totalH <= scrH || scrH < 1) { jpgv_stops[0] = 0; jpgv_stopCount = 1; return; }\n';
  fn += '  int maxY = totalH - scrH;\n';
  fn += '  int halfH = scrH / 2;\n';
  fn += '  jpgv_stops[jpgv_stopCount++] = 0;\n';
  fn += '  if (halfH >= maxY) { jpgv_stops[jpgv_stopCount++] = jpgv_snapStop(maxY); }\n';
  fn += '  else {\n';
  fn += '    jpgv_stops[jpgv_stopCount++] = jpgv_snapStop(halfH);\n';
  fn += '    int y = halfH;\n';
  fn += '    while (jpgv_stopCount < 63) {\n';
  fn += '      y += scrH;\n';
  fn += '      if (y >= maxY) { jpgv_stops[jpgv_stopCount++] = jpgv_snapStop(maxY); break; }\n';
  fn += '      int sy = jpgv_snapStop(y);\n';
  fn += '      if (sy <= jpgv_stops[jpgv_stopCount - 1]) sy = jpgv_stops[jpgv_stopCount - 1] + 1;\n';
  fn += '      if (sy > maxY) sy = maxY;\n';
  fn += '      jpgv_stops[jpgv_stopCount++] = sy;\n';
  fn += '      y = sy;\n';
  fn += '    }\n';
  fn += '  }\n';
  fn += '  if (jpgv_stops[jpgv_stopCount - 1] < maxY) jpgv_stops[jpgv_stopCount - 1] = maxY;\n';
  fn += '}\n';
  fn += 'static int jpgv_scrollY = 0;\n';

  // --- dir-list navigation (fixes leading-zero mismatch e.g. 09.jpg vs 9.jpg) ---
  fn += 'static long jpgv_extractNum(const String& fle) {\n';
  fn += '  int n = fle.length();\n';
  fn += '  int i = n - 1;\n';
  fn += '  while (i >= 0 && (fle[i] < \'0\' || fle[i] > \'9\')) i--;\n';
  fn += '  if (i < 0) return -1L;\n';
  fn += '  int end = i + 1;\n';
  fn += '  while (i >= 0 && fle[i] >= \'0\' && fle[i] <= \'9\') i--;\n';
  fn += '  return fle.substring(i + 1, end).toInt();\n';
  fn += '}\n';
  fn += 'static void jpgv_buildFileList(const String& dirp) {\n';
  fn += '  if (jpgv_dirCache == dirp && jpgv_fileList) return;\n';
  fn += '  jpgv_dirCache = dirp;\n';
  fn += '  if (jpgv_fileList) { delete[] jpgv_fileList; jpgv_fileList = nullptr; }\n';
  fn += '  jpgv_fileCount = 0; jpgv_fileIdx = -1;\n';
  fn += '  File root = SD.open(dirp);\n';
  fn += '  if (!root || !root.isDirectory()) { if (root) root.close(); return; }\n';
  fn += '  int cap = 512;\n';
  fn += '  String* arr = new String[cap];\n';
  fn += '  if (!arr) { root.close(); return; }\n';
  fn += '  int n = 0;\n';
  fn += '  File entry = root.openNextFile();\n';
  fn += '  while (entry) {\n';
  fn += '    if (!entry.isDirectory() && n < cap) {\n';
  fn += '      String nm = String(entry.name());\n';
  fn += '      int psl = nm.lastIndexOf(\'/\'); if (psl >= 0) nm.remove(0, psl + 1);\n';
  fn += '      String ename = nm; ename.toLowerCase();\n';
  fn += '      if (ename.endsWith(".jpg") || ename.endsWith(".jpeg") || ename.endsWith(".bmp")) {\n';
  fn += '        arr[n++] = nm;\n';
  fn += '      }\n';
  fn += '    }\n';
  fn += '    entry = root.openNextFile();\n';
  fn += '  }\n';
  fn += '  root.close();\n';
  fn += '  // insertion sort by extracted number then name\n';
  fn += '  for (int i = 1; i < n; i++) {\n';
  fn += '    String tmp = arr[i]; long tn = jpgv_extractNum(tmp);\n';
  fn += '    int j = i - 1;\n';
  fn += '    while (j >= 0) {\n';
  fn += '      long jn = jpgv_extractNum(arr[j]);\n';
  fn += '      bool go = (tn >= 0 && jn >= 0) ? (jn > tn) : ((jn == tn) ? (arr[j] > tmp) : (jn < 0));\n';
  fn += '      if (!go) break;\n';
  fn += '      arr[j + 1] = arr[j]; j--;\n';
  fn += '    }\n';
  fn += '    arr[j + 1] = tmp;\n';
  fn += '  }\n';
  fn += '  jpgv_fileList = arr;\n';
  fn += '  jpgv_fileCount = n;\n';
  fn += '  Serial.printf("[JPGV] dir %s n=%d", dirp.c_str(), n);\n';
  fn += '  for (int i = 0; i < n && i < 8; i++) Serial.printf(" [%d]%s", i, arr[i].c_str());\n';
  fn += '  Serial.printf("%s\\n", (n > 8) ? " ..." : "");\n';
  fn += '}\n';
  fn += 'static String jpgv_numPath(const String& cur, int delta) {\n';
  fn += '  int sl = cur.lastIndexOf(\'/\');\n';
  fn += '  String dirp = (sl >= 0) ? cur.substring(0, sl + 1) : "/";\n';
  fn += '  String fle = (sl >= 0) ? cur.substring(sl + 1) : cur;\n';
  fn += '  jpgv_buildFileList(dirp);\n';
  fn += '  if (!jpgv_fileList || jpgv_fileCount <= 0) return "";\n';
  fn += '  int curIdx = -1;\n';
  fn += '  for (int i = 0; i < jpgv_fileCount; i++) {\n';
  fn += '    if (jpgv_fileList[i] == fle) { curIdx = i; break; }\n';
  fn += '  }\n';
  fn += '  if (curIdx < 0) {\n';
  fn += '    long curNum = jpgv_extractNum(fle);\n';
  fn += '    for (int i = 0; i < jpgv_fileCount; i++) {\n';
  fn += '      if (jpgv_extractNum(jpgv_fileList[i]) == curNum) { curIdx = i; break; }\n';
  fn += '    }\n';
  fn += '  }\n';
  fn += '  if (curIdx < 0) { Serial.printf("[JPGV] cur-not-in-list %s (n=%d)\\n", fle.c_str(), jpgv_fileCount); return ""; }\n';
  fn += '  jpgv_fileIdx = curIdx;\n';
  fn += '  int target = curIdx + delta;\n';
  fn += '  if (target < 0 || target >= jpgv_fileCount) return "";\n';
  fn += '  jpgv_fileIdx = target;\n';
  fn += '  return dirp + jpgv_fileList[target];\n';
  fn += '}\n';

  fn += 'static void jpgvNotFoundToast(const String& path) {\n';
  fn += '  extern SdFont sdFont;\n';
  fn += '  int sl = path.lastIndexOf(\'/\');\n';
  fn += '  String fn = (sl >= 0) ? path.substring(sl + 1) : path;\n';
  fn += '  bool useSdf = sdFont.isLoaded();\n';
  fn += '  String msg = useSdf ? (String("\\xe6\\x9c\\xaa\\xe6\\x89\\xbe\\xe5\\x88\\xb0 ") + fn) : (String("Not found: ") + fn);\n';
  fn += '  int pw = tft.width(), ph = tft.height();\n';
  fn += '  int fh = useSdf ? sdFont.getCharHeight() : 16;\n';
  fn += '  if (fh < 8) fh = 16;\n';
  fn += '  int th = fh + 28; if (th < 40) th = 40;\n';
  fn += '  int mw = useSdf ? sdFont.measureString(msg.c_str()) : (tft.setTextSize(2), tft.textWidth(msg.c_str()));\n';
  fn += '  int tw = mw + 36; if (tw > pw - 16) tw = pw - 16; if (tw < 110) tw = 110;\n';
  fn += '  int px = (pw - tw) / 2, py = (ph - th) / 2;\n';
  fn += '  tft.fillRoundRect(px + 3, py + 3, tw, th, 6, 0x0102);\n';
  fn += '  tft.fillRoundRect(px, py, tw, th, 6, 0x0000);\n';
  fn += '  tft.drawRoundRect(px, py, tw, th, 6, 0xF800);\n';
  fn += '  tft.drawFastHLine(px + 5, py + 1, tw - 10, 0x3CE7);\n';
  fn += '  tft.drawFastHLine(px + 5, py + th - 2, tw - 10, 0x0102);\n';
  fn += '  if (useSdf) {\n';
  fn += '    sdFont.drawString(px + (tw - mw) / 2, py + (th - fh) / 2, msg.c_str(), 0xF800);\n';
  fn += '  } else {\n';
  fn += '    tft.setTextDatum(4);\n';
  fn += '    tft.setTextColor(0xF800, 0x0000);\n';
  fn += '    tft.drawString(msg.c_str(), pw / 2, py + th / 2);\n';
  fn += '    tft.setTextDatum(0);\n';
  fn += '    tft.setTextSize(1);\n';
  fn += '  }\n';
  fn += '  delay(1400);\n';
  fn += '}\n';
  fn += 'static uint32_t jpgv_rd32(const uint8_t* p) { return (uint32_t)p[0]|((uint32_t)p[1]<<8)|((uint32_t)p[2]<<16)|((uint32_t)p[3]<<24); }\n';
  fn += 'static uint16_t jpgv_rd16(const uint8_t* p) { return (uint16_t)((uint16_t)p[0]|((uint16_t)p[1]<<8)); }\n';
  fn += 'static bool jpgv_decodeBmp(uint8_t* data, int sz) {\n';
  fn += '  if (sz < 54 || data[0] != 0x42 || data[1] != 0x4D) return false;\n';
  fn += '  uint32_t pixelOffset = jpgv_rd32(data + 10);\n';
  fn += '  int32_t bmpW = (int32_t)jpgv_rd32(data + 18);\n';
  fn += '  int32_t bmpH = (int32_t)jpgv_rd32(data + 22);\n';
  fn += '  uint16_t bpp = jpgv_rd16(data + 28);\n';
  fn += '  uint32_t compression = jpgv_rd32(data + 30);\n';
  fn += '  if (compression != 0 || (bpp != 24 && bpp != 32)) return false;\n';
  fn += '  if (bmpW <= 0) return false;\n';
  fn += '  bool topDown = (bmpH < 0);\n';
  fn += '  int absH = topDown ? -bmpH : bmpH;\n';
  fn += '  int bypp = bpp / 8;\n';
  fn += '  int rowSize = ((bmpW * bypp + 3) & ~3);\n';
  fn += '  if ((int)pixelOffset + rowSize * absH > sz) return false;\n';
  fn += '  if (jpgv_decBuf) { free(jpgv_decBuf); jpgv_decBuf = nullptr; }\n';
  fn += '  jpgv_decBuf = (uint16_t*)ps_malloc((size_t)bmpW * absH * 2);\n';
  fn += '  if (!jpgv_decBuf) return false;\n';
  fn += '  jpgv_decW = bmpW; jpgv_decH = absH;\n';
  fn += '  for (int y = 0; y < absH; y++) {\n';
  fn += '    int srcY = topDown ? y : (absH - 1 - y);\n';
  fn += '    uint8_t* row = data + pixelOffset + (size_t)srcY * rowSize;\n';
  fn += '    for (int x = 0; x < bmpW; x++) {\n';
  fn += '      uint8_t b = row[x * bypp];\n';
  fn += '      uint8_t g = row[x * bypp + 1];\n';
  fn += '      uint8_t r = row[x * bypp + 2];\n';
  fn += '      { uint16_t v = ((uint16_t)(r >> 3) << 11) | ((uint16_t)(g >> 2) << 5) | (b >> 3); jpgv_decBuf[y * bmpW + x] = (uint16_t)((v >> 8) | (v << 8)); }\n';
  fn += '    }\n';
  fn += '  }\n';
  fn += '  return true;\n';
  fn += '}\n';
  fn += 'static void jpgv_gridBuild();\n';
  fn += 'static void jpgv_gridCell(int idx, int& x0, int& y0);\n';
  fn += 'static void jpgv_postProcess() {\n';
  fn += '  jpgv_despeckle();\n';
  fn += '  jpgv_bleach();\n';
  fn += '  jpgv_calcInkThr();\n';
  fn += '  jpgv_calcBg();\n';
  fn += '  jpgv_trimMarginsV();\n';
  fn += '  jpgv_trimGutter();\n';
  fn += '  jpgv_findSpread();\n';
  fn += '}\n';
  fn += 'static bool jpgv_redecodeFull() {\n';
  fn += '  if (!jpgv_scaledDecode) return true;\n';
  fn += '  if (jpgv_path.length() == 0) return false;\n';
  fn += '  File f = SD.open(jpgv_path, FILE_READ);\n';
  fn += '  if (!f) return false;\n';
  fn += '  uint16_t* nb = nullptr; int nw = 0, nh = 0; bool ip = false; bool ws = false;\n';
  fn += '  int scrW0 = tft.width();\n';
  fn += '  bool ok = espJpegDecode565File(f, jpgv_path, scrW0 * 2, nb, nw, nh, 1, &ip, false, &ws);\n';
  fn += '  if (!ok || ip || !nb) { if (nb) free(nb); return false; }\n';
  fn += '  if (jpgv_decBuf) free(jpgv_decBuf);\n';
  fn += '  jpgv_decBuf = nb; jpgv_decW = nw; jpgv_decH = nh;\n';
  fn += '  jpgv_imgW = nw; jpgv_imgH = nh;\n';
  fn += '  jpgv_scaledDecode = false;\n';
  fn += '  jpgv_postProcess();\n';
  fn += '  Serial.printf("[JPGV] redecode full %dx%d\\n", nw, nh);\n';
  fn += '  return true;\n';
  fn += '}\n';
  fn += 'static bool jpgv_show(const String& path) {\n';
  fn += '  int kz = jpgv_keepZoom;\n';
  fn += '  jpgv_keepZoom = 0;\n';
  fn += '  String lower = path; lower.toLowerCase();\n';
  fn += '  bool isBmp = lower.endsWith(".bmp");\n';
  fn += '  File f = SD.open(path, FILE_READ);\n';
  fn += '  if (!f) { tft.fillRoundRect(8,8,tft.width()-16,22,6,0x0000); tft.drawRoundRect(8,8,tft.width()-16,22,6,0xF800); tft.setTextColor(0xF800,0x0000); tft.setCursor(14,16); tft.print("Cannot open file"); delay(1500); return false; }\n';
  fn += '  int sz = f.size();\n';
  fn += '  if (epubCovRelease) epubCovRelease();\n';
  fn += '  if (epubFontRelease) epubFontRelease();\n';
  fn += '  if (epubImgRelease) epubImgRelease();\n';
  fn += '  if (jpgv_decBuf) { free(jpgv_decBuf); jpgv_decBuf = nullptr; }\n';
  fn += '  int decW = 0, decH = 0;\n';
  fn += '  if (isBmp) {\n';
  fn += '    uint8_t* fileBuf = (uint8_t*)ps_malloc(sz + 16);\n';
  fn += '    if (!fileBuf) { f.close(); tft.fillRoundRect(8,8,tft.width()-16,22,6,0x0000); tft.drawRoundRect(8,8,tft.width()-16,22,6,0xF800); tft.setTextColor(0xF800,0x0000); tft.setCursor(14,16); tft.printf("Too big: %d KB (free %uK)", sz/1024, (unsigned)(ESP.getFreePsram()/1024)); delay(1500); return false; }\n';
  fn += '    int rd = jpgv_readWhole(f, path, fileBuf, sz);\n';
  fn += '    f.close();\n';
  fn += '    if (rd != sz) { Serial.printf("[JPGV] read FAIL rd=%d/%d\\n", rd, sz); free(fileBuf); tft.fillRoundRect(8,8,tft.width()-16,22,6,0x0000); tft.drawRoundRect(8,8,tft.width()-16,22,6,0xF800); tft.setTextColor(0xF800,0x0000); tft.setCursor(14,16); tft.printf("SD read fail %d/%d", rd, sz); delay(1500); return false; }\n';
  fn += '    if (!jpgv_decodeBmp(fileBuf, sz)) { free(fileBuf); tft.fillRoundRect(8,8,tft.width()-16,22,6,0x0000); tft.drawRoundRect(8,8,tft.width()-16,22,6,0xF800); tft.setTextColor(0xF800,0x0000); tft.setCursor(14,16); tft.print("BMP decode fail"); delay(1500); return false; }\n';
  fn += '    free(fileBuf);\n';
  fn += '    decW = jpgv_decW; decH = jpgv_decH;\n';
  fn += '    jpgv_scaledDecode = false;\n';
  fn += '  } else {\n';
  fn += '    int scrW0 = tft.width();\n';
  fn += '    bool wasProg = false;\n';
  fn += '    bool wasScaled = false;\n';
  fn += '    if (!espJpegDecode565File(f, path, scrW0 * 2, jpgv_decBuf, decW, decH, 1, &wasProg, kz == 0, &wasScaled)) {\n';
  fn += '      if (!wasProg) { tft.fillRoundRect(8,8,tft.width()-16,22,6,0x0000); tft.drawRoundRect(8,8,tft.width()-16,22,6,0xF800); tft.setTextColor(0xF800,0x0000); tft.setCursor(14,16); tft.print("JPEG decode fail"); delay(1500); return false; }\n';
  fn += '      f = SD.open(path, FILE_READ);\n';
  fn += '      if (!f) { tft.fillRoundRect(8,8,tft.width()-16,22,6,0x0000); tft.drawRoundRect(8,8,tft.width()-16,22,6,0xF800); tft.setTextColor(0xF800,0x0000); tft.setCursor(14,16); tft.print("JPEG decode fail"); delay(1500); return false; }\n';
  fn += '      uint8_t* fileBuf = (uint8_t*)ps_malloc(sz + 16);\n';
  fn += '      if (!fileBuf) { f.close(); tft.fillRoundRect(8,8,tft.width()-16,22,6,0x0000); tft.drawRoundRect(8,8,tft.width()-16,22,6,0xF800); tft.setTextColor(0xF800,0x0000); tft.setCursor(14,16); tft.printf("Too big: %d KB (free %uK)", sz/1024, (unsigned)(ESP.getFreePsram()/1024)); delay(1500); return false; }\n';
  fn += '      int rd = jpgv_readWhole(f, path, fileBuf, sz);\n';
  fn += '      f.close();\n';
  fn += '      if (rd != sz) { Serial.printf("[JPGV] read FAIL rd=%d/%d\\n", rd, sz); free(fileBuf); tft.fillRoundRect(8,8,tft.width()-16,22,6,0x0000); tft.drawRoundRect(8,8,tft.width()-16,22,6,0xF800); tft.setTextColor(0xF800,0x0000); tft.setCursor(14,16); tft.printf("SD read fail %d/%d", rd, sz); delay(1500); return false; }\n';
  fn += '      bool ok2 = espJpegDecode565(fileBuf, sz, scrW0 * 2, jpgv_decBuf, decW, decH, 1);\n';
  fn += '      free(fileBuf);\n';
  fn += '      wasScaled = false;\n';
  fn += '      if (!ok2) { tft.fillRoundRect(8,8,tft.width()-16,22,6,0x0000); tft.drawRoundRect(8,8,tft.width()-16,22,6,0xF800); tft.setTextColor(0xF800,0x0000); tft.setCursor(14,16); tft.print("JPEG decode fail"); delay(1500); return false; }\n';
  fn += '    }\n';
  fn += '    jpgv_decW = decW; jpgv_decH = decH;\n';
  fn += '    jpgv_scaledDecode = wasScaled;\n';
  fn += '  }\n';
  fn += '  int scrW = tft.width();\n';
  fn += '  jpgv_imgW = decW; jpgv_imgH = decH;\n';
  fn += '  jpgv_postProcess();\n';
  fn += '  jpgv_pageIdx = 0;\n';
  fn += '  jpgv_calcPage();\n';
  fn += '  jpgv_viewY = 0;\n';
  fn += '  jpgv_zoom = 0; jpgv_zoomX = 0; jpgv_zoomY = 0; jpgv_grid = 0; jpgv_cellIdx = 0;\n';
  fn += '  jpgv_scrollY = 0;\n';
  fn += '  jpgv_computeStops(jpgv_imgH, jpgv_rowsPerPage);\n';
  fn += '  jpgv_stopIdx = 0;\n';
  fn += '  jpgv_path = path;\n';
  fn += '  if (kz != 0) {\n';
  fn += '    if (kz < 0 && jpgv_pages == 2) {\n';
  fn += '      jpgv_pageIdx = 1;\n';
  fn += '      jpgv_calcPage(); jpgv_computeStops(jpgv_imgH, jpgv_rowsPerPage);\n';
  fn += '    }\n';
  fn += '    jpgv_zoom = 1;\n';
  fn += '    jpgv_gridBuild();\n';
  fn += '    int t2 = jpgv_gridCols * jpgv_gridRows;\n';
  fn += '    if (jpgv_grid && t2 > 0) {\n';
  fn += '      jpgv_cellIdx = (kz > 0) ? 0 : (t2 - 1);\n';
  fn += '      jpgv_gridCell(jpgv_cellIdx, jpgv_zoomX, jpgv_zoomY);\n';
  fn += '    } else { jpgv_zoomX = jpgv_pnX0; jpgv_zoomY = 0; }\n';
  fn += '  }\n';
  fn += '  jpgv_renderView();\n';
  fn += '  Serial.printf("[JPGV] show %s dec=%dx%d win=%dx%d gutter=%d pnX0=%d pnW=%d minLum=%d inkThr=%d pages=%d rpp=%d\\n", path.c_str(), decW, decH, jpgv_imgW, jpgv_imgH, jpgv_gutterL, jpgv_pnX0, jpgv_pnW, jpgv_minLum, jpgv_inkThr, jpgv_pages, jpgv_rowsPerPage);\n';
  fn += '  return true;\n';
  fn += '}\n';
  fn += 'static void jpgv_gridBuild() {\n';
  fn += '  jpgv_grid = 0; jpgv_gridCols = 0; jpgv_gridRows = 0; jpgv_cellIdx = 0;\n';
  fn += '  if (jpgv_imgW <= 0 || jpgv_imgH <= 0) return;\n';
  fn += '  jpgv_pageWindow();\n';
  fn += '  jpgv_trimPageH();\n';
  fn += '  int scrW = tft.width(), scrH = tft.height();\n';
  fn += '  jpgv_gridCols = (jpgv_pnW + scrW - 1) / scrW;\n';
  fn += '  jpgv_gridRows = (jpgv_imgH + scrH - 1) / scrH;\n';
  fn += '  if (jpgv_gridCols < 1) jpgv_gridCols = 1;\n';
  fn += '  if (jpgv_gridRows < 1) jpgv_gridRows = 1;\n';
  fn += '  if (jpgv_gridCols == 1 && jpgv_gridRows == 1) return;\n';
  fn += '  jpgv_grid = 1;\n';
  fn += '}\n';
  fn += 'static void jpgv_gridCell(int idx, int& x0, int& y0) {\n';
  fn += '  int scrW = tft.width(), scrH = tft.height();\n';
  fn += '  int r = idx / jpgv_gridCols, c = idx % jpgv_gridCols;\n';
  fn += '  if (jpgv_gridRTL) c = jpgv_gridCols - 1 - c;\n';
  fn += '  x0 = jpgv_pnX0 + c * scrW;\n';
  fn += '  int maxX = jpgv_pnX0 + jpgv_pnW - scrW; if (maxX < jpgv_pnX0) maxX = jpgv_pnX0;\n';
  fn += '  if (x0 > maxX) x0 = maxX;\n';
  fn += '  y0 = r * scrH;\n';
  fn += '  int maxY = jpgv_imgH - scrH; if (maxY < 0) maxY = 0;\n';
  fn += '  if (y0 > maxY) y0 = maxY;\n';
  fn += '}\n';
  fn += 'static void jpgv_zoomToggle() {\n';
  fn += '  jpgv_zoom = !jpgv_zoom;\n';
  fn += '  int scrW = tft.width(), scrH = tft.height();\n';
  fn += '  if (jpgv_zoom) {\n';
  fn += '    if (jpgv_scaledDecode) {\n';
  fn += '      if (jpgv_redecodeFull()) {\n';
  fn += '        jpgv_pageIdx = 0;\n';
  fn += '        jpgv_calcPage();\n';
  fn += '        jpgv_computeStops(jpgv_imgH, jpgv_rowsPerPage);\n';
  fn += '      }\n';
  fn += '    }\n';
  fn += '    jpgv_gridBuild();\n';
  fn += '    if (jpgv_grid) {\n';
  fn += '      jpgv_zoomX = 0; jpgv_zoomY = 0;\n';
  fn += '      jpgv_gridCell(0, jpgv_zoomX, jpgv_zoomY);\n';
  fn += '    } else {\n';
  fn += '    int minX = jpgv_pnX0;\n';
  fn += '    int maxX = jpgv_pnX0 + jpgv_pnW - scrW; if (maxX < minX) maxX = minX;\n';
  fn += '    int maxY = jpgv_imgH - scrH; if (maxY < 0) maxY = 0;\n';
  fn += '    jpgv_zoomX = minX + (maxX - minX) / 2;\n';
  fn += '    jpgv_zoomY = jpgv_viewY + (jpgv_rowsPerPage - scrH) / 2;\n';
  fn += '    if (jpgv_zoomY > maxY) jpgv_zoomY = maxY; if (jpgv_zoomY < 0) jpgv_zoomY = 0;\n';
  fn += '    }\n';
  fn += '  } else {\n';
  fn += '    jpgv_viewY = (int)(((long)jpgv_zoomY + jpgv_rowsPerPage / 2) / jpgv_rowsPerPage) * jpgv_rowsPerPage;\n';
  fn += '    int maxY = jpgv_imgH - jpgv_rowsPerPage; if (maxY < 0) maxY = 0;\n';
  fn += '    if (jpgv_viewY > maxY) jpgv_viewY = maxY; if (jpgv_viewY < 0) jpgv_viewY = 0;\n';
  fn += '    jpgv_computeStops(jpgv_imgH, jpgv_rowsPerPage);\n';
  fn += '    int best = 0, bd = 1 << 30;\n';
  fn += '    for (int i = 0; i < jpgv_stopCount; i++) { int d = jpgv_stops[i] - jpgv_viewY; if (d < 0) d = -d; if (d < bd) { bd = d; best = i; } }\n';
  fn += '    if (jpgv_stopCount > 0) { jpgv_stopIdx = best; jpgv_scrollY = jpgv_stops[best]; jpgv_viewY = jpgv_scrollY; }\n';
  fn += '  }\n';
  fn += '  jpgv_renderView();\n';
  fn += '}\n';
  fn += 'static void jpgv_pan(int dx, int dy) {\n';
  fn += '  if (!jpgv_zoom || !jpgv_decBuf) return;\n';
  fn += '  int scrW = tft.width(), scrH = tft.height();\n';
  fn += '  int minX = jpgv_pnX0;\n';
  fn += '  int maxX = jpgv_pnX0 + jpgv_pnW - scrW; if (maxX < minX) maxX = minX;\n';
  fn += '  int maxY = jpgv_imgH - scrH; if (maxY < 0) maxY = 0;\n';
  fn += '  jpgv_zoomX += dx * scrW; if (jpgv_zoomX > maxX) jpgv_zoomX = maxX; if (jpgv_zoomX < minX) jpgv_zoomX = minX;\n';
  fn += '  jpgv_zoomY += dy * scrH; if (jpgv_zoomY > maxY) jpgv_zoomY = maxY; if (jpgv_zoomY < 0) jpgv_zoomY = 0;\n';
  fn += '  jpgv_renderView();\n';
  fn += '}\n';
  fn += 'static bool jpgv_toggleRTL() {\n';
  fn += '  if (!jpgv_zoom) return false;\n';
  fn += '  bool physLeft = (jpgv_pages == 2) ? (jpgv_pnX0 <= 0) : true;\n';
  fn += '  jpgv_gridRTL = !jpgv_gridRTL;\n';
  fn += '  if (jpgv_pages == 2) {\n';
  fn += '    jpgv_pageWindow();\n';
  fn += '    bool nowLeft = (jpgv_pnX0 <= 0);\n';
  fn += '    if (nowLeft != physLeft) { jpgv_pageIdx = 1 - jpgv_pageIdx; jpgv_pageWindow(); }\n';
  fn += '  }\n';
  fn += '  if (jpgv_grid && jpgv_gridCols > 0) {\n';
  fn += '    int r = jpgv_cellIdx / jpgv_gridCols;\n';
  fn += '    int c = jpgv_cellIdx % jpgv_gridCols;\n';
  fn += '    jpgv_cellIdx = r * jpgv_gridCols + (jpgv_gridCols - 1 - c);\n';
  fn += '    jpgv_gridCell(jpgv_cellIdx, jpgv_zoomX, jpgv_zoomY);\n';
  fn += '  }\n';
  fn += '  jpgv_renderView();\n';
  fn += '  return true;\n';
  fn += '}\n';
  fn += 'static bool jpgv_cellStep(int dir) {\n';
  fn += '  if (!jpgv_grid) return false;\n';
  fn += '  int total = jpgv_gridCols * jpgv_gridRows;\n';
  fn += '  jpgv_cellIdx += dir;\n';
  fn += '  if (jpgv_cellIdx >= total) {\n';
  fn += '    jpgv_cellIdx = total - 1;\n';
  fn += '    if (jpgv_pageIdx + 1 < jpgv_pages) {\n';
  fn += '      jpgv_pageIdx++;\n';
  fn += '      jpgv_calcPage(); jpgv_computeStops(jpgv_imgH, jpgv_rowsPerPage);\n';
  fn += '      jpgv_gridBuild();\n';
  fn += '      if (jpgv_grid) { jpgv_cellIdx = 0; jpgv_gridCell(0, jpgv_zoomX, jpgv_zoomY); }\n';
  fn += '      jpgv_renderView(); return true;\n';
  fn += '    }\n';
  fn += '    String next = jpgv_numPath(jpgv_path, 1);\n';
  fn += '    jpgv_keepZoom = 1;\n';
  fn += '    if (next.length() > 0) { if (jpgv_show(next)) return true; }\n';
  fn += '    else if (next.length() > 0) jpgvNotFoundToast(next);\n';
  fn += '    jpgv_renderView(); return true;\n';
  fn += '  }\n';
  fn += '  if (jpgv_cellIdx < 0) {\n';
  fn += '    jpgv_cellIdx = 0;\n';
  fn += '    if (jpgv_pageIdx > 0) {\n';
  fn += '      jpgv_pageIdx--;\n';
  fn += '      jpgv_calcPage(); jpgv_computeStops(jpgv_imgH, jpgv_rowsPerPage);\n';
  fn += '      jpgv_gridBuild();\n';
  fn += '      int t2 = jpgv_gridCols * jpgv_gridRows;\n';
  fn += '      if (jpgv_grid && t2 > 0) { jpgv_cellIdx = t2 - 1; jpgv_gridCell(jpgv_cellIdx, jpgv_zoomX, jpgv_zoomY); }\n';
  fn += '      jpgv_renderView(); return true;\n';
  fn += '    }\n';
  fn += '    String prev = jpgv_numPath(jpgv_path, -1);\n';
  fn += '    jpgv_keepZoom = -1;\n';
  fn += '    if (prev.length() > 0) { if (jpgv_show(prev)) return true; }\n';
  fn += '    else jpgv_renderView();\n';
  fn += '    jpgv_renderView(); return true;\n';
  fn += '  }\n';
  fn += '  jpgv_gridCell(jpgv_cellIdx, jpgv_zoomX, jpgv_zoomY);\n';
  fn += '  jpgv_renderView();\n';
  fn += '  return true;\n';
  fn += '}\n';
  fn += 'static bool jpgv_next() {\n';
  fn += '  if (jpgv_zoom && jpgv_decBuf) {\n';
  fn += '    if (jpgv_grid) return jpgv_cellStep(1);\n';
  fn += '    int scrH = tft.height();\n';
  fn += '    int step = scrH * 3 / 4;\n';
  fn += '    int maxY = jpgv_imgH - scrH; if (maxY < 0) maxY = 0;\n';
  fn += '    jpgv_zoomY += step; if (jpgv_zoomY > maxY) jpgv_zoomY = maxY;\n';
  fn += '    jpgv_renderView(); return true;\n';
  fn += '  }\n';
  fn += '  if (jpgv_stopCount <= 0) return false;\n';
  fn += '  jpgv_stopIdx++;\n';
  fn += '  if (jpgv_stopIdx >= jpgv_stopCount) {\n';
  fn += '    jpgv_stopIdx = jpgv_stopCount - 1;\n';
  fn += '    if (jpgv_pageIdx + 1 < jpgv_pages) {\n';
  fn += '      jpgv_pageIdx++;\n';
  fn += '      jpgv_calcPage(); jpgv_computeStops(jpgv_imgH, jpgv_rowsPerPage);\n';
  fn += '      jpgv_stopIdx = 0; jpgv_scrollY = 0; jpgv_viewY = 0;\n';
  fn += '      jpgv_renderView(); return true;\n';
  fn += '    }\n';
  fn += '    String next = jpgv_numPath(jpgv_path, 1);\n';
  fn += '    if (next.length() > 0) {\n';
  fn += '      if (jpgv_show(next)) return true; jpgv_renderView(); return true;\n';
  fn += '    }\n';
  fn += '    return true;\n';
  fn += '  }\n';
  fn += '  jpgv_scrollY = jpgv_stops[jpgv_stopIdx];\n';
  fn += '  jpgv_viewY = jpgv_scrollY;\n';
  fn += '  jpgv_renderView();\n';
  fn += '  return true;\n';
  fn += '}\n';
  fn += 'static bool jpgv_prev() {\n';
  fn += '  if (jpgv_zoom && jpgv_decBuf) {\n';
  fn += '    if (jpgv_grid) return jpgv_cellStep(-1);\n';
  fn += '    int scrH = tft.height();\n';
  fn += '    int step = scrH * 3 / 4;\n';
  fn += '    jpgv_zoomY -= step; if (jpgv_zoomY < 0) jpgv_zoomY = 0;\n';
  fn += '    jpgv_renderView(); return true;\n';
  fn += '  }\n';
  fn += '  if (jpgv_stopCount <= 0) return false;\n';
  fn += '  jpgv_stopIdx--;\n';
  fn += '  if (jpgv_stopIdx < 0) {\n';
  fn += '    jpgv_stopIdx = 0;\n';
  fn += '    if (jpgv_pageIdx > 0) {\n';
  fn += '      jpgv_pageIdx--;\n';
  fn += '      jpgv_calcPage(); jpgv_computeStops(jpgv_imgH, jpgv_rowsPerPage);\n';
  fn += '      if (jpgv_stopCount > 0) { jpgv_stopIdx = jpgv_stopCount - 1; jpgv_scrollY = jpgv_stops[jpgv_stopIdx]; jpgv_viewY = jpgv_scrollY; }\n';
  fn += '      jpgv_renderView(); return true;\n';
  fn += '    }\n';
  fn += '    String prev = jpgv_numPath(jpgv_path, -1);\n';
  fn += '    if (prev.length() > 0) {\n';
  fn += '      if (jpgv_show(prev)) {\n';
  fn += '        jpgv_stopIdx = jpgv_stopCount - 1;\n';
  fn += '        jpgv_scrollY = jpgv_stops[jpgv_stopIdx];\n';
  fn += '        jpgv_viewY = jpgv_scrollY;\n';
  fn += '      } else {\n';
  fn += '        jpgvNotFoundToast(prev);\n';
  fn += '        jpgv_scrollY = 0; jpgv_viewY = 0;\n';
  fn += '      }\n';
  fn += '      jpgv_renderView();\n';
  fn += '      return true;\n';
  fn += '    }\n';
  fn += '    jpgv_scrollY = 0; jpgv_viewY = 0;\n';
  fn += '    jpgv_renderView();\n';
  fn += '    return true;\n';
  fn += '  }\n';
  fn += '  jpgv_scrollY = jpgv_stops[jpgv_stopIdx];\n';
  fn += '  jpgv_viewY = jpgv_scrollY;\n';
  fn += '  jpgv_renderView();\n';
  fn += '  return true;\n';
  fn += '}\n';  fn += 'static void jpgv_exit() {\n';
  fn += '  if (jpgv_fileList) { delete[] jpgv_fileList; jpgv_fileList = nullptr; }\n';
  fn += '  jpgv_fileCount = 0; jpgv_fileIdx = -1; jpgv_dirCache = "";\n';
  fn += '  if (jpgv_decBuf) { free(jpgv_decBuf); jpgv_decBuf = nullptr; }\n';
  fn += '  jpgv_imgW = 0; jpgv_imgH = 0; jpgv_viewY = 0; jpgv_scrollY = 0; jpgv_zoom = 0; jpgv_zoomX = 0; jpgv_zoomY = 0; jpgv_rowsPerPage = 1;\n';
  fn += '  jpgv_stopIdx = 0; jpgv_stopCount = 0;\n';
  fn += '  jpgv_scaledDecode = false;\n';
  fn += '  jpgv_path = "";\n';
  fn += '  if (epubFontRestore) epubFontRestore();\n';
  fn += '}\n';
  generator.addFunction('jpgvInfra', fn);
}

Arduino.forBlock['sd_jpg_viewer_open'] = function(block, generator) {
  const path = generator.valueToCode(block, 'PATH', generator.ORDER_ATOMIC) || '""';
  addJpegViewerInfra(generator);
  return ['jpgv_show(String(' + path + '))', generator.ORDER_ATOMIC];
};

Arduino.forBlock['sd_jpg_viewer_next'] = function(block, generator) {
  addJpegViewerInfra(generator);
  return ['jpgv_next()', generator.ORDER_ATOMIC];
};

Arduino.forBlock['sd_jpg_viewer_prev'] = function(block, generator) {
  addJpegViewerInfra(generator);
  return ['jpgv_prev()', generator.ORDER_ATOMIC];
};

Arduino.forBlock['sd_jpg_viewer_zoom'] = function(block, generator) {
  addJpegViewerInfra(generator);
  return 'jpgv_zoomToggle();\n';
};

Arduino.forBlock['sd_jpg_viewer_pan'] = function(block, generator) {
  const dx = generator.valueToCode(block, 'DX', generator.ORDER_ATOMIC) || '0';
  const dy = generator.valueToCode(block, 'DY', generator.ORDER_ATOMIC) || '0';
  addJpegViewerInfra(generator);
  return 'jpgv_pan(' + dx + ', ' + dy + ');\n';
};

Arduino.forBlock['sd_jpg_viewer_dir'] = function(block, generator) {
  addJpegViewerInfra(generator);
  return ['jpgv_toggleRTL()', generator.ORDER_ATOMIC];
};

Arduino.forBlock['sd_jpg_viewer_exit'] = function(block, generator) {
  addJpegViewerInfra(generator);
  return 'jpgv_exit();\n';
};
