// _varMonitorAttached: object names are registered and renamed by thingsboardAttach.
function thingsboardEnsure(generator){generator.addLibrary('thingsboard_network','#if defined(ESP8266)\n#include <ESP8266WiFi.h>\n#else\n#include <WiFi.h>\n#endif');generator.addLibrary('thingsboard_mqtt','#include <Arduino_MQTT_Client.h>');generator.addLibrary('thingsboard_include','#include <ThingsBoard.h>');}
function thingsboardName(block){var field=block.getField('VAR');return field?field.getText():(block.getFieldValue('VAR')||'tb');}
function thingsboardAttach(block){if(block._thingsboardAttached)return;block._thingsboardAttached=true;block._thingsboardLast=block.getFieldValue('VAR')||'tb';if(typeof registerVariableToBlockly==='function')registerVariableToBlockly(block._thingsboardLast,'ThingsBoard');var field=block.getField('VAR');if(!field)return;var original=field.onFinishEditing_;field.onFinishEditing_=function(newName){if(typeof original==='function')original.call(this,newName);if(newName&&newName!==block._thingsboardLast&&typeof renameVariableInBlockly==='function'){renameVariableInBlockly(block,block._thingsboardLast,newName,'ThingsBoard');block._thingsboardLast=newName;}};}
Arduino.forBlock['thingsboard_init']=function(block,generator){thingsboardEnsure(generator);thingsboardAttach(block);var n=block.getFieldValue('VAR')||'tb',s=generator.valueToCode(block,'SERVER',generator.ORDER_ATOMIC)||'"demo.thingsboard.io"',t=generator.valueToCode(block,'TOKEN',generator.ORDER_ATOMIC)||'"DEVICE_TOKEN"',p=generator.valueToCode(block,'PORT',generator.ORDER_ATOMIC)||'1883',z=generator.valueToCode(block,'SIZE',generator.ORDER_ATOMIC)||'256';generator.addObject('thingsboard_net_'+n,'WiFiClient '+n+'_network;');generator.addObject('thingsboard_mqtt_'+n,'Arduino_MQTT_Client '+n+'_mqtt('+n+'_network);');generator.addObject('thingsboard_'+n,'ThingsBoard '+n+'('+n+'_mqtt, '+z+', '+z+');');generator.addLoopBegin('thingsboard_loop_'+n,n+'.loop();');return n+'.connect('+s+', '+t+', '+p+');\n';};
Arduino.forBlock['thingsboard_connect']=function(block,generator){thingsboardEnsure(generator);var n=thingsboardName(block),s=generator.valueToCode(block,'SERVER',generator.ORDER_ATOMIC)||'"demo.thingsboard.io"',t=generator.valueToCode(block,'TOKEN',generator.ORDER_ATOMIC)||'"DEVICE_TOKEN"',p=generator.valueToCode(block,'PORT',generator.ORDER_ATOMIC)||'1883';return [n+'.connect('+s+', '+t+', '+p+')',generator.ORDER_FUNCTION_CALL];};
Arduino.forBlock['thingsboard_send']=function(block,generator){thingsboardEnsure(generator);var n=thingsboardName(block),k=block.getFieldValue('KIND')||'sendTelemetryData',key=generator.valueToCode(block,'KEY',generator.ORDER_ATOMIC)||'"temperature"',v=generator.valueToCode(block,'VALUE',generator.ORDER_NONE)||'0';return [n+'.'+k+'(String('+key+').c_str(), '+v+')',generator.ORDER_FUNCTION_CALL];};
Arduino.forBlock['thingsboard_send_json']=function(block,generator){thingsboardEnsure(generator);var n=thingsboardName(block),k=block.getFieldValue('KIND')||'sendTelemetryString',j=generator.valueToCode(block,'JSON',generator.ORDER_ATOMIC)||'"{}"';return [n+'.'+k+'(String('+j+').c_str())',generator.ORDER_FUNCTION_CALL];};
Arduino.forBlock['thingsboard_connected']=function(block,generator){thingsboardEnsure(generator);return [thingsboardName(block)+'.connected()',generator.ORDER_FUNCTION_CALL];};
Arduino.forBlock['thingsboard_disconnect']=function(block,generator){thingsboardEnsure(generator);return thingsboardName(block)+'.disconnect();\n';};
