// _varMonitorAttached: object names are registered and renamed by arduinoGfxAttach.
function arduinoGfxEnsure(generator){generator.addLibrary('arduino_gfx_include','#include <Arduino_GFX_Library.h>');}
function arduinoGfxName(block){var field=block.getField('VAR');return field?field.getText():(block.getFieldValue('VAR')||'gfx');}
function arduinoGfxAttach(block){if(block._arduinoGfxAttached)return;block._arduinoGfxAttached=true;block._arduinoGfxLast=block.getFieldValue('VAR')||'gfx';if(typeof registerVariableToBlockly==='function')registerVariableToBlockly(block._arduinoGfxLast,'Arduino_GFX');var field=block.getField('VAR');if(!field)return;var original=field.onFinishEditing_;field.onFinishEditing_=function(newName){if(typeof original==='function')original.call(this,newName);if(newName&&newName!==block._arduinoGfxLast&&typeof renameVariableInBlockly==='function'){renameVariableInBlockly(block,block._arduinoGfxLast,newName,'Arduino_GFX');block._arduinoGfxLast=newName;}};}
Arduino.forBlock['arduino_gfx_init']=function(block,generator){arduinoGfxEnsure(generator);arduinoGfxAttach(block);var n=block.getFieldValue('VAR')||'gfx',d=block.getFieldValue('DRIVER')||'Arduino_ILI9341',dc=block.getFieldValue('DC')||'8',cs=block.getFieldValue('CS')||'9',rst=block.getFieldValue('RST')||'7',r=block.getFieldValue('ROTATION')||'0',ips=block.getFieldValue('IPS')==='TRUE'?'true':'false';generator.addObject('arduino_gfx_bus_'+n,'Arduino_DataBus *'+n+'_bus = new Arduino_HWSPI('+dc+', '+cs+');');generator.addObject('arduino_gfx_'+n,'Arduino_GFX *'+n+' = new '+d+'('+n+'_bus, '+rst+', '+r+', '+ips+');');generator.addSetupBegin('arduino_gfx_begin_'+n,n+'->begin();');return '';};
Arduino.forBlock['arduino_gfx_fill']=function(block,generator){arduinoGfxEnsure(generator);var n=arduinoGfxName(block),c=generator.valueToCode(block,'COLOR',generator.ORDER_ATOMIC)||'RGB565_BLACK';return n+'->fillScreen('+c+');\n';};
Arduino.forBlock['arduino_gfx_draw_line']=function(block,generator){arduinoGfxEnsure(generator);var n=arduinoGfxName(block),x0=generator.valueToCode(block,'X0',generator.ORDER_ATOMIC)||'0',y0=generator.valueToCode(block,'Y0',generator.ORDER_ATOMIC)||'0',x1=generator.valueToCode(block,'X1',generator.ORDER_ATOMIC)||'10',y1=generator.valueToCode(block,'Y1',generator.ORDER_ATOMIC)||'10',c=generator.valueToCode(block,'COLOR',generator.ORDER_ATOMIC)||'RGB565_WHITE';return n+'->drawLine('+x0+', '+y0+', '+x1+', '+y1+', '+c+');\n';};
Arduino.forBlock['arduino_gfx_draw_rect']=function(block,generator){arduinoGfxEnsure(generator);var n=arduinoGfxName(block),m=block.getFieldValue('MODE')||'drawRect',x=generator.valueToCode(block,'X',generator.ORDER_ATOMIC)||'0',y=generator.valueToCode(block,'Y',generator.ORDER_ATOMIC)||'0',w=generator.valueToCode(block,'W',generator.ORDER_ATOMIC)||'10',h=generator.valueToCode(block,'H',generator.ORDER_ATOMIC)||'10',c=generator.valueToCode(block,'COLOR',generator.ORDER_ATOMIC)||'RGB565_WHITE';return n+'->'+m+'('+x+', '+y+', '+w+', '+h+', '+c+');\n';};
Arduino.forBlock['arduino_gfx_draw_circle']=function(block,generator){arduinoGfxEnsure(generator);var n=arduinoGfxName(block),m=block.getFieldValue('MODE')||'drawCircle',x=generator.valueToCode(block,'X',generator.ORDER_ATOMIC)||'0',y=generator.valueToCode(block,'Y',generator.ORDER_ATOMIC)||'0',r=generator.valueToCode(block,'R',generator.ORDER_ATOMIC)||'10',c=generator.valueToCode(block,'COLOR',generator.ORDER_ATOMIC)||'RGB565_WHITE';return n+'->'+m+'('+x+', '+y+', '+r+', '+c+');\n';};
Arduino.forBlock['arduino_gfx_text_style']=function(block,generator){arduinoGfxEnsure(generator);var n=arduinoGfxName(block),c=generator.valueToCode(block,'COLOR',generator.ORDER_ATOMIC)||'RGB565_WHITE',b=generator.valueToCode(block,'BG',generator.ORDER_ATOMIC)||'RGB565_BLACK',s=generator.valueToCode(block,'SIZE',generator.ORDER_ATOMIC)||'1',w=block.getFieldValue('WRAP')==='TRUE'?'true':'false';return n+'->setTextColor('+c+', '+b+');\n'+n+'->setTextSize('+s+');\n'+n+'->setTextWrap('+w+');\n';};
Arduino.forBlock['arduino_gfx_text']=function(block,generator){arduinoGfxEnsure(generator);var n=arduinoGfxName(block),x=generator.valueToCode(block,'X',generator.ORDER_ATOMIC)||'0',y=generator.valueToCode(block,'Y',generator.ORDER_ATOMIC)||'0',o=block.getFieldValue('OP')||'print',t=generator.valueToCode(block,'TEXT',generator.ORDER_NONE)||'""';return n+'->setCursor('+x+', '+y+');\n'+n+'->'+o+'('+t+');\n';};
Arduino.forBlock['arduino_gfx_control']=function(block,generator){arduinoGfxEnsure(generator);var n=arduinoGfxName(block),a=block.getFieldValue('ACTION')||'setRotation',v=generator.valueToCode(block,'VALUE',generator.ORDER_ATOMIC)||'0';return n+'->'+a+'('+v+');\n';};
Arduino.forBlock['arduino_gfx_dimension']=function(block,generator){arduinoGfxEnsure(generator);var n=arduinoGfxName(block),d=block.getFieldValue('DIM')||'width';return [n+'->'+d+'()',generator.ORDER_FUNCTION_CALL];};
Arduino.forBlock['arduino_gfx_rgb565']=function(block,generator){var r=generator.valueToCode(block,'R',generator.ORDER_ATOMIC)||'0',g=generator.valueToCode(block,'G',generator.ORDER_ATOMIC)||'0',b=generator.valueToCode(block,'B',generator.ORDER_ATOMIC)||'0';return ['((uint16_t)((('+r+' & 0xF8) << 8) | (('+g+' & 0xFC) << 3) | ('+b+' >> 3)))',generator.ORDER_BITWISE_OR];};
