// _varMonitorAttached: receiver names are registered and renamed by irEspAttach.
function irEspEnsureSend(generator){generator.addLibrary('ir_esp_core','#include <IRremoteESP8266.h>');generator.addLibrary('ir_esp_send','#include <IRsend.h>');}
function irEspEnsureRecv(generator){generator.addLibrary('ir_esp_core','#include <IRremoteESP8266.h>');generator.addLibrary('ir_esp_recv','#include <IRrecv.h>');generator.addLibrary('ir_esp_utils','#include <IRutils.h>');}
function irEspName(block){var field=block.getField('VAR');return field?field.getText():(block.getFieldValue('VAR')||'irRecv');}
function irEspAttach(block,typeName,fallback){if(block._irEspAttached)return;block._irEspAttached=true;block._irEspLast=block.getFieldValue('VAR')||fallback;if(typeof registerVariableToBlockly==='function')registerVariableToBlockly(block._irEspLast,typeName);var field=block.getField('VAR');if(!field)return;var original=field.onFinishEditing_;field.onFinishEditing_=function(newName){if(typeof original==='function')original.call(this,newName);if(newName&&newName!==block._irEspLast&&typeof renameVariableInBlockly==='function'){renameVariableInBlockly(block,block._irEspLast,newName,typeName);block._irEspLast=newName;}};}
Arduino.forBlock['ir_esp_send_init']=function(block,generator){irEspEnsureSend(generator);irEspAttach(block,'IRsend','irSend');var n=block.getFieldValue('VAR')||'irSend',p=block.getFieldValue('PIN')||'4';generator.addObject('ir_esp_send_'+n,'IRsend '+n+'('+p+');');generator.addSetupBegin('ir_esp_send_begin_'+n,n+'.begin();');return '';};
Arduino.forBlock['ir_esp_send_code']=function(block,generator){irEspEnsureSend(generator);var n=irEspName(block),p=block.getFieldValue('PROTOCOL')||'sendNEC',c=generator.valueToCode(block,'CODE',generator.ORDER_ATOMIC)||'0',b=generator.valueToCode(block,'BITS',generator.ORDER_ATOMIC)||'32',r=generator.valueToCode(block,'REPEATS',generator.ORDER_ATOMIC)||'0';return n+'.'+p+'((uint64_t)'+c+', '+b+', '+r+');\n';};
Arduino.forBlock['ir_esp_send_raw']=function(block,generator){irEspEnsureSend(generator);var n=irEspName(block),a=(block.getFieldValue('ARRAY')||'rawData').replace(/[^A-Za-z0-9_]/g,''),l=generator.valueToCode(block,'LENGTH',generator.ORDER_ATOMIC)||'0',k=generator.valueToCode(block,'KHZ',generator.ORDER_ATOMIC)||'38';return n+'.sendRaw('+a+', '+l+', '+k+');\n';};
Arduino.forBlock['ir_esp_recv_init']=function(block,generator){irEspEnsureRecv(generator);irEspAttach(block,'IRrecv','irRecv');var n=block.getFieldValue('VAR')||'irRecv',p=block.getFieldValue('PIN')||'14',b=generator.valueToCode(block,'BUFFER',generator.ORDER_ATOMIC)||'1024',t=generator.valueToCode(block,'TIMEOUT',generator.ORDER_ATOMIC)||'50';generator.addObject('ir_esp_recv_'+n,'IRrecv '+n+'('+p+', '+b+', '+t+', true);');generator.addObject('ir_esp_results_'+n,'decode_results '+n+'_results;');generator.addSetupBegin('ir_esp_recv_begin_'+n,n+'.enableIRIn();');return '';};
Arduino.forBlock['ir_esp_when_received']=function(block,generator){irEspEnsureRecv(generator);var n=irEspName(block),body=generator.statementToCode(block,'DO')||'';return 'if ('+n+'.decode(&'+n+'_results)) {\n'+body+'  '+n+'.resume();\n}\n';};
Arduino.forBlock['ir_esp_received_data']=function(block,generator){irEspEnsureRecv(generator);var n=irEspName(block),d=block.getFieldValue('DATA')||'value';var map={value:n+'_results.value',bits:n+'_results.bits',decode_type:n+'_results.decode_type',repeat:n+'_results.repeat',overflow:n+'_results.overflow',text:'resultToHumanReadableBasic(&'+n+'_results)',source:'resultToSourceCode(&'+n+'_results)'};return [map[d]||map.value,generator.ORDER_ATOMIC];};
