// _varMonitorAttached: object names are registered and renamed by dynamixelAttach.
function dynamixelEnsure(generator){generator.addLibrary('dynamixel_include','#include <Dynamixel2Arduino.h>');generator.addMacro('dynamixel_namespace','using namespace ControlTableItem;');}
function dynamixelName(block){var field=block.getField('VAR');return field?field.getText():(block.getFieldValue('VAR')||'dxl');}
function dynamixelAttach(block){if(block._dynamixelAttached)return;block._dynamixelAttached=true;block._dynamixelLast=block.getFieldValue('VAR')||'dxl';if(typeof registerVariableToBlockly==='function')registerVariableToBlockly(block._dynamixelLast,'Dynamixel2Arduino');var field=block.getField('VAR');if(!field)return;var original=field.onFinishEditing_;field.onFinishEditing_=function(newName){if(typeof original==='function')original.call(this,newName);if(newName&&newName!==block._dynamixelLast&&typeof renameVariableInBlockly==='function'){renameVariableInBlockly(block,block._dynamixelLast,newName,'Dynamixel2Arduino');block._dynamixelLast=newName;}};}
Arduino.forBlock['dynamixel_init']=function(block,generator){dynamixelEnsure(generator);dynamixelAttach(block);var n=block.getFieldValue('VAR')||'dxl',s=block.getFieldValue('SERIAL')||'Serial1',d=block.getFieldValue('DIR')||'2',b=block.getFieldValue('BAUD')||'57600',p=block.getFieldValue('PROTOCOL')||'2.0';generator.addObject('dynamixel_'+n,'Dynamixel2Arduino '+n+'('+s+', '+d+');');generator.addSetupBegin('dynamixel_begin_'+n,n+'.begin('+b+');\n'+n+'.setPortProtocolVersion('+p+');');return '';};
Arduino.forBlock['dynamixel_set_mode']=function(block,generator){dynamixelEnsure(generator);var n=dynamixelName(block),id=generator.valueToCode(block,'ID',generator.ORDER_ATOMIC)||'1',m=block.getFieldValue('MODE')||'OP_POSITION';return n+'.torqueOff('+id+');\n'+n+'.setOperatingMode('+id+', '+m+');\n'+n+'.torqueOn('+id+');\n';};
Arduino.forBlock['dynamixel_goal']=function(block,generator){dynamixelEnsure(generator);var n=dynamixelName(block),id=generator.valueToCode(block,'ID',generator.ORDER_ATOMIC)||'1',g=block.getFieldValue('GOAL')||'setGoalPosition',v=generator.valueToCode(block,'VALUE',generator.ORDER_ATOMIC)||'0',u=block.getFieldValue('UNIT')||'UNIT_RAW';return n+'.'+g+'('+id+', '+v+', '+u+');\n';};
Arduino.forBlock['dynamixel_read']=function(block,generator){dynamixelEnsure(generator);var n=dynamixelName(block),id=generator.valueToCode(block,'ID',generator.ORDER_ATOMIC)||'1',d=block.getFieldValue('DATA')||'getPresentPosition',u=block.getFieldValue('UNIT')||'UNIT_RAW';return [n+'.'+d+'('+id+', '+u+')',generator.ORDER_FUNCTION_CALL];};
Arduino.forBlock['dynamixel_action']=function(block,generator){dynamixelEnsure(generator);var n=dynamixelName(block),id=generator.valueToCode(block,'ID',generator.ORDER_ATOMIC)||'1',a=block.getFieldValue('ACTION')||'torqueOn';return n+'.'+a+'('+id+');\n';};
Arduino.forBlock['dynamixel_ping']=function(block,generator){dynamixelEnsure(generator);var n=dynamixelName(block),id=generator.valueToCode(block,'ID',generator.ORDER_ATOMIC)||'1';return [n+'.ping('+id+')',generator.ORDER_FUNCTION_CALL];};
Arduino.forBlock['dynamixel_control_item']=function(block,generator){dynamixelEnsure(generator);var n=dynamixelName(block),id=generator.valueToCode(block,'ID',generator.ORDER_ATOMIC)||'1',i=block.getFieldValue('ITEM')||'PROFILE_VELOCITY',v=generator.valueToCode(block,'VALUE',generator.ORDER_ATOMIC)||'0';return n+'.writeControlTableItem('+i+', '+id+', '+v+');\n';};
