// _varMonitorAttached: server names are registered and renamed by elegantOtaAttach.
function elegantOtaEnsure(generator,asyncMode){if(asyncMode)generator.addMacro('elegant_ota_async','#define ELEGANTOTA_USE_ASYNC_WEBSERVER 1');generator.addLibrary('elegant_ota_include','#include <ElegantOTA.h>');}
function elegantOtaName(block){var field=block.getField('VAR');return field?field.getText():(block.getFieldValue('VAR')||'otaServer');}
function elegantOtaAttach(block){if(block._elegantOtaAttached)return;block._elegantOtaAttached=true;block._elegantOtaLast=block.getFieldValue('VAR')||'otaServer';if(typeof registerVariableToBlockly==='function')registerVariableToBlockly(block._elegantOtaLast,'ElegantOTAServer');var field=block.getField('VAR');if(!field)return;var original=field.onFinishEditing_;field.onFinishEditing_=function(newName){if(typeof original==='function')original.call(this,newName);if(newName&&newName!==block._elegantOtaLast&&typeof renameVariableInBlockly==='function'){renameVariableInBlockly(block,block._elegantOtaLast,newName,'ElegantOTAServer');block._elegantOtaLast=newName;}};}
Arduino.forBlock['elegant_ota_init']=function(block,generator){var a=block.getFieldValue('MODE')==='async';elegantOtaEnsure(generator,a);elegantOtaAttach(block);var n=elegantOtaName(block),p=generator.valueToCode(block,'PORT',generator.ORDER_ATOMIC)||'80',u=generator.valueToCode(block,'USERNAME',generator.ORDER_ATOMIC)||'""',pw=generator.valueToCode(block,'PASSWORD',generator.ORDER_ATOMIC)||'""',r=block.getFieldValue('REBOOT')==='TRUE'?'true':'false';generator.addObject('elegant_ota_server_'+n,(a?'AsyncWebServer ':'WebServer ')+n+'('+p+');');generator.addSetupEnd('elegant_ota_begin_'+n,'ElegantOTA.setAutoReboot('+r+');\nElegantOTA.begin(&'+n+', String('+u+').c_str(), String('+pw+').c_str());\n'+n+'.begin();');if(!a)generator.addLoopBegin('elegant_ota_server_loop_'+n,n+'.handleClient();');generator.addLoopBegin('elegant_ota_loop','ElegantOTA.loop();');return '';};
Arduino.forBlock['elegant_ota_auth']=function(block,generator){elegantOtaEnsure(generator,false);var u=generator.valueToCode(block,'USERNAME',generator.ORDER_ATOMIC)||'""',p=generator.valueToCode(block,'PASSWORD',generator.ORDER_ATOMIC)||'""';return 'ElegantOTA.setAuth(String('+u+').c_str(), String('+p+').c_str());\n';};
Arduino.forBlock['elegant_ota_on_start']=function(block,generator){elegantOtaEnsure(generator,false);var body=generator.statementToCode(block,'DO')||'';generator.addSetupEnd('elegant_ota_on_start','ElegantOTA.onStart([]() {\n'+body+'});');return '';};
Arduino.forBlock['elegant_ota_on_progress']=function(block,generator){elegantOtaEnsure(generator,false);var body=generator.statementToCode(block,'DO')||'';generator.addSetupEnd('elegant_ota_on_progress','ElegantOTA.onProgress([](size_t _ailyOtaCurrent, size_t _ailyOtaFinal) {\n'+body+'});');return '';};
Arduino.forBlock['elegant_ota_on_end']=function(block,generator){elegantOtaEnsure(generator,false);var body=generator.statementToCode(block,'DO')||'';generator.addSetupEnd('elegant_ota_on_end','ElegantOTA.onEnd([](bool _ailyOtaSuccess) {\n'+body+'});');return '';};
Arduino.forBlock['elegant_ota_callback_value']=function(block,generator){var v=block.getFieldValue('VALUE')||'_ailyOtaCurrent';if(v==='percent')return ['(_ailyOtaFinal ? (100.0 * _ailyOtaCurrent / _ailyOtaFinal) : 0)',generator.ORDER_CONDITIONAL];return [v,generator.ORDER_ATOMIC];};
