// _varMonitorAttached: object names are registered and renamed by ggwaveAttach.
function ggwaveEnsure(generator){generator.addLibrary('ggwave_include','#include <ggwave/ggwave.h>');}
function ggwaveName(block){var field=block.getField('VAR');return field?field.getText():(block.getFieldValue('VAR')||'ggwave');}
function ggwaveAttach(block){if(block._ggwaveAttached)return;block._ggwaveAttached=true;block._ggwaveLast=block.getFieldValue('VAR')||'ggwave';if(typeof registerVariableToBlockly==='function')registerVariableToBlockly(block._ggwaveLast,'ggwave_Instance');var field=block.getField('VAR');if(!field)return;var original=field.onFinishEditing_;field.onFinishEditing_=function(newName){if(typeof original==='function')original.call(this,newName);if(newName&&newName!==block._ggwaveLast&&typeof renameVariableInBlockly==='function'){renameVariableInBlockly(block,block._ggwaveLast,newName,'ggwave_Instance');block._ggwaveLast=newName;}};}
Arduino.forBlock['ggwave_init']=function(block,generator){ggwaveEnsure(generator);ggwaveAttach(block);var n=block.getFieldValue('VAR')||'ggwave',m=block.getFieldValue('MODE')||'GGWAVE_OPERATING_MODE_RX_AND_TX',r=generator.valueToCode(block,'RATE',generator.ORDER_ATOMIC)||'48000',f=generator.valueToCode(block,'FRAME',generator.ORDER_ATOMIC)||'1024',p=generator.valueToCode(block,'PAYLOAD',generator.ORDER_ATOMIC)||'-1';generator.addObject('ggwave_instance_'+n,'ggwave_Instance '+n+' = -1;');generator.addObject('ggwave_buffers_'+n,'uint8_t *'+n+'_waveform = nullptr;\nint '+n+'_waveform_bytes = 0;\nchar '+n+'_payload[257] = {0};\nint '+n+'_payload_length = 0;');generator.addSetupBegin('ggwave_init_'+n,'ggwave_Parameters '+n+'_params = ggwave_getDefaultParameters();\n'+n+'_params.payloadLength = '+p+';\n'+n+'_params.sampleRateInp = '+r+';\n'+n+'_params.sampleRateOut = '+r+';\n'+n+'_params.sampleRate = '+r+';\n'+n+'_params.samplesPerFrame = '+f+';\n'+n+'_params.sampleFormatInp = GGWAVE_SAMPLE_FORMAT_I16;\n'+n+'_params.sampleFormatOut = GGWAVE_SAMPLE_FORMAT_I16;\n'+n+'_params.operatingMode = '+m+';\n'+n+' = ggwave_init('+n+'_params);');return '';};
Arduino.forBlock['ggwave_encode']=function(block,generator){ggwaveEnsure(generator);var n=ggwaveName(block),t=generator.valueToCode(block,'TEXT',generator.ORDER_ATOMIC)||'"hello"',p=block.getFieldValue('PROTOCOL')||'GGWAVE_PROTOCOL_AUDIBLE_FAST',v=generator.valueToCode(block,'VOLUME',generator.ORDER_ATOMIC)||'25';return '{\n  String _ailyGgText = String('+t+');\n  int _ailyGgNeeded = ggwave_encode('+n+', _ailyGgText.c_str(), _ailyGgText.length(), '+p+', '+v+', NULL, 1);\n  if (_ailyGgNeeded > 0) {\n    uint8_t *_ailyGgBuffer = (uint8_t*)realloc('+n+'_waveform, _ailyGgNeeded);\n    if (_ailyGgBuffer) { '+n+'_waveform = _ailyGgBuffer; '+n+'_waveform_bytes = ggwave_encode('+n+', _ailyGgText.c_str(), _ailyGgText.length(), '+p+', '+v+', '+n+'_waveform, 0); }\n  }\n}\n';};
Arduino.forBlock['ggwave_waveform']=function(block,generator){ggwaveEnsure(generator);var n=ggwaveName(block),d=block.getFieldValue('DATA')||'waveform';return [d==='bytes'?n+'_waveform_bytes':n+'_waveform',generator.ORDER_ATOMIC];};
Arduino.forBlock['ggwave_decode']=function(block,generator){ggwaveEnsure(generator);var n=ggwaveName(block),b=(block.getFieldValue('BUFFER')||'audioBuffer').replace(/[^A-Za-z0-9_]/g,''),z=generator.valueToCode(block,'BYTES',generator.ORDER_ATOMIC)||'0';return ['('+n+'_payload_length = ggwave_ndecode('+n+', '+b+', '+z+', '+n+'_payload, sizeof('+n+'_payload) - 1), '+n+'_payload['+n+'_payload_length > 0 ? '+n+'_payload_length : 0] = 0, '+n+'_payload_length)',generator.ORDER_COMMA];};
Arduino.forBlock['ggwave_decoded']=function(block,generator){ggwaveEnsure(generator);var n=ggwaveName(block),d=block.getFieldValue('DATA')||'text';return [d==='length'?n+'_payload_length':'String('+n+'_payload)',generator.ORDER_FUNCTION_CALL];};
Arduino.forBlock['ggwave_free']=function(block,generator){ggwaveEnsure(generator);var n=ggwaveName(block);return 'ggwave_free('+n+');\n'+n+' = -1;\nfree('+n+'_waveform);\n'+n+'_waveform = nullptr;\n'+n+'_waveform_bytes = 0;\n';};
